// Stitch memo cards in English. Written for Rowtine: no text taken from outside sources.
// Keys = identifiers from catalog.js.
export const STITCH_MEMO_EN = {
  'cr-ch': {
    name: 'Chain stitch (with slip knot)',
    abbr: ['ch'],
    steps: [
      'Make a loop in the yarn, about 10 cm from the end.',
      'Pull a loop of the working yarn through it: this is the slip knot.',
      'Slide the slip knot onto the hook and tighten it gently.',
      'Yarn over.',
      'Pull the yarn through the loop on the hook: you have made 1 chain.',
      'Repeat the yarn over and pull through until you reach the number of chains required.',
    ],
    tip: 'Do not count the slip knot or the loop on the hook: count the small Vs on the front of the chain.',
  },
  'cr-slst': {
    name: 'Slip stitch',
    abbr: ['sl st', 'ss (UK)'],
    steps: [
      'Insert the hook into the next stitch, under both loops.',
      'Yarn over.',
      'Pull the yarn through the stitch and the loop on the hook in one motion.',
    ],
    tip: 'A slip stitch adds almost no height: use it to close a round or to move along the row. Keep it loose, or it will be hard to work into on the next round.',
  },
  'cr-sc': {
    name: 'Single crochet (US) / double crochet (UK)',
    abbr: ['sc (US)', 'dc (UK)'],
    steps: [
      'Insert the hook into the next stitch, under both loops.',
      'Yarn over and pull a loop back through the stitch: you now have 2 loops on the hook.',
      'Yarn over again.',
      'Pull through both loops at once.',
    ],
    tip: 'US and UK names differ: a US single crochet is a UK double crochet. Check which one your pattern uses. Count your stitches at the end of the row.',
  },
  'cr-hdc': {
    name: 'Half double crochet (US) / half treble crochet (UK)',
    abbr: ['hdc (US)', 'htr (UK)'],
    steps: [
      'Yarn over.',
      'Insert the hook into the next stitch, under both loops.',
      'Yarn over and pull a loop back through the stitch: you now have 3 loops on the hook.',
      'Yarn over again.',
      'Pull through all 3 loops at once.',
    ],
    tip: 'The turning chain for this stitch is 2 chains. Depending on the pattern, it counts as the first stitch or not: check before you insert the hook.',
  },
  'cr-dc': {
    name: 'Double crochet (US) / treble crochet (UK)',
    abbr: ['dc (US)', 'tr (UK)'],
    steps: [
      'Yarn over.',
      'Insert the hook into the next stitch, under both loops.',
      'Yarn over and pull a loop back through the stitch: you now have 3 loops on the hook.',
      'Yarn over and pull through the first 2 loops: 2 loops remain.',
      'Yarn over and pull through the last 2 loops.',
    ],
    tip: 'A turning chain of 3 usually counts as the first stitch: work the next one into the second stitch of the row, or your work will get wider.',
  },
  'cr-tr': {
    name: 'Treble crochet (US) / double treble crochet (UK)',
    abbr: ['tr (US)', 'dtr (UK)'],
    steps: [
      'Yarn over twice.',
      'Insert the hook into the next stitch, under both loops.',
      'Yarn over and pull a loop back through the stitch: you now have 4 loops on the hook.',
      'Yarn over and pull through 2 loops: 3 loops remain.',
      'Yarn over and pull through 2 loops: 2 loops remain.',
      'Yarn over and pull through the last 2 loops.',
    ],
    tip: 'You work the loops off 2 at a time, three times in a row. The turning chain for this stitch is 4 chains.',
  },
  'cr-inc': {
    name: 'Increase',
    abbr: ['inc'],
    steps: [
      'Work 1 single crochet (UK double crochet) into the next stitch.',
      'Insert the hook into that same stitch again.',
      'Work a second single crochet: one stitch below now holds 2.',
    ],
    tip: 'Each increase adds 1 stitch, and the motion is the same with taller stitches. In the round, stagger your increases from one round to the next, or the circle turns into a polygon.',
  },
  'cr-dec': {
    name: 'Decrease: single crochet 2 together (US) / double crochet 2 together (UK)',
    abbr: ['dec', 'sc2tog (US)', 'dc2tog (UK)'],
    steps: [
      'Insert the hook into the next stitch.',
      'Yarn over and pull a loop back through the stitch: you now have 2 loops on the hook.',
      'Insert the hook into the following stitch.',
      'Yarn over and pull a loop back through the stitch: you now have 3 loops on the hook.',
      'Yarn over again.',
      'Pull through all 3 loops at once: 2 stitches have become 1.',
    ],
    tip: 'In amigurumi, the invisible decrease leaves a smaller gap: insert the hook into the front loops only of both stitches at once, then finish like a single crochet (US) / double crochet (UK).',
  },
  'cr-magic-ring': {
    name: 'Magic ring (magic circle)',
    abbr: ['MR'],
    steps: [
      'Wrap the yarn around two fingers to form a loop, with the tail crossing over the working yarn.',
      'Slide the hook into the loop, catch the working yarn and pull it through.',
      'Chain 1 to lock it: this chain does not count as a stitch.',
      'Work the required number of single crochets (UK double crochets) into the ring, often 6, going under the loop and the tail together.',
      'Pull the tail to close the ring.',
      'Close the round with a slip stitch into the first stitch, or carry on in a spiral.',
    ],
    tip: 'Weave in the tail, changing direction several times: it is what holds the ring shut, and if it slips, the ring opens up again.',
  },
  'cr-rounds': {
    name: 'Working in rows and in the round',
    abbr: ['tch'],
    steps: [
      'In rows, make the turning chain at the end of the row: 1 chain for single crochet, 2 for half double, 3 for double (US terms).',
      'Turn the work and start the next row.',
      'In joined rounds, finish each round with a slip stitch into the first stitch of the round.',
      'Chain to the height of the new round, then carry on without turning the work.',
      'In a spiral, do not join the round: work straight into the first stitch of the previous round.',
      'Place a marker in the first stitch of each round and move it up every new round.',
    ],
    tip: 'Depending on the pattern, the turning chain counts as a stitch or not: read the instructions again, this is the most common reason for a row that gains or loses a stitch.',
  },
  'cr-flo-blo': {
    name: 'Front loop only / back loop only',
    abbr: ['FLO', 'BLO'],
    steps: [
      'Look at the top of the stitch: it forms a sideways V made of two loops.',
      'Find the front loop, closest to you, and the back loop, furthest away.',
      'To work in the front loop, insert the hook under that single loop.',
      'To work in the back loop, slip the hook between the two loops and under the back loop alone.',
      'Finish the stitch as usual.',
    ],
    tip: 'Front and back are relative to you as you hold the work, not to the right side of the fabric. The loop you leave free forms a raised line.',
  },
  'cr-color-change': {
    name: 'Colour change',
    abbr: [],
    steps: [
      'Start the last stitch in the old colour and stop before its final yarn over.',
      'Drop the old colour, keeping about 10 cm of yarn if you cut it.',
      'Pick up the new colour, leaving a tail of about 10 cm.',
      'Make the final yarn over with the new colour and pull through: the stitch is complete.',
      'Carry on with the new colour.',
      'At the end, weave in both tails, each into stitches of its own colour.',
    ],
    tip: 'In joined rounds, change colour on the joining slip stitch: work it with the new colour and the join shows less.',
  },
  'cr-shell': {
    name: 'Shell stitch',
    abbr: ['sh'],
    steps: [
      'Work 1 single crochet (UK double crochet) into the first stitch.',
      'Skip the number of stitches given in the pattern, often 2.',
      'Work the required number of double crochets (UK trebles) into the next stitch, often 5.',
      'Skip the same number of stitches again.',
      'Work 1 single crochet into the next stitch to anchor the shell.',
      'Repeat steps 2 to 5 to the end of the row.',
    ],
    tip: 'With 5 stitches per shell and 2 skipped on each side, each repeat takes 6 stitches: your base row needs a multiple of 6 stitches plus 1, or the last shell will sit crooked.',
  },
  'cr-picot': {
    name: 'Picot',
    abbr: [],
    steps: [
      'Chain 3, or the number given in the pattern.',
      'Insert the hook into the first of these chains, the third from the hook.',
      'Yarn over.',
      'Pull the yarn through the chain and the loop on the hook in one motion: the picot is closed with a slip stitch.',
    ],
    tip: 'Some patterns close the picot into the top of the stitch before it rather than into the chain: follow the pattern, as the base of the picot does not sit in the same place.',
  },
  'cr-popcorn': {
    name: 'Popcorn stitch',
    abbr: ['pc'],
    steps: [
      'Work 5 double crochets (UK trebles) into the same stitch, or the number given in the pattern.',
      'Take the hook out of the loop and enlarge it a little so that it does not unravel.',
      'Insert the hook from front to back into the top of the first of the 5 stitches.',
      'Catch the loop you left waiting with the hook.',
      'Pull it through the top of the first stitch: the group closes and bulges toward the front.',
      'Chain 1 to lock the popcorn.',
    ],
    tip: 'The popcorn pops out on the side you insert the hook from: front to back makes it bulge toward you. Do not confuse it with the puff stitch, whose loops are worked off together.',
  },
  'cr-puff': {
    name: 'Puff stitch',
    abbr: [],
    steps: [
      'Yarn over and insert the hook into the stitch.',
      'Yarn over and pull up a long loop, about the height of a half double crochet (UK half treble).',
      'Repeat these two steps 3 more times in the same stitch: you now have 9 loops on the hook.',
      'Yarn over and pull through all 9 loops at once.',
      'Chain 1 to close the stitch.',
    ],
    tip: 'If the loops will not pass, they are too short or too tight: pull them all up to the same height and hold them against the hook with your index finger.',
  },
  'cr-post': {
    name: 'Front and back post double crochet (US) / front and back post treble crochet (UK)',
    abbr: ['FPdc (US)', 'BPdc (US)', 'FPtr (UK)', 'BPtr (UK)'],
    steps: [
      'Yarn over.',
      'For front post, insert the hook from front to back on one side of the post of the stitch below, then back to the front on the other side: the hook passes behind the post.',
      'Yarn over and pull a loop around the post: you now have 3 loops on the hook.',
      'Yarn over and pull through the first 2 loops.',
      'Yarn over and pull through the last 2 loops.',
      'For back post, after the yarn over, insert the hook from back to front on one side of the post, then to the back again on the other side: the hook passes in front of the post.',
      'Finish the stitch as for front post, with steps 3 to 5.',
    ],
    tip: 'Do not work into the top of the stitch whose post you wrapped: it is hidden behind the raised stitch, and skipping it keeps your stitch count right.',
  },
  'kn-co-long-tail': {
    name: 'Long-tail cast-on',
    abbr: ['CO'],
    steps: [
      'Measure out a length of free yarn for the tail: allow about 2 to 3 cm per stitch to cast on, depending on the yarn weight.',
      'Make a slip knot at that point and put it on the needle: it counts as the first stitch.',
      'Hold the needle in your right hand, wrap the tail around your left thumb and the working yarn over your left index finger, with both ends held in your palm.',
      'Take the needle tip up through the loop on your thumb, under the front strand.',
      'Catch the index finger strand with the tip, going over it.',
      'Bring that strand back through the thumb loop.',
      'Drop the thumb loop, then spread your thumb under the tail to snug the stitch onto the needle.',
      'Repeat steps 4 to 7 until you reach the number of stitches required.',
    ],
    tip: 'If the tail runs out before the end, start again with a longer tail rather than adding yarn. Snug the stitches without choking the needle: they should still slide.',
  },
  'kn-co-tubular': {
    name: 'Tubular cast-on (Italian cast-on)',
    abbr: [],
    steps: [
      'Use a needle 1 or 2 sizes smaller than for the ribbing, and leave a tail 3 to 4 times the width to cast on.',
      'Make a slip knot and put it on the needle, held in your right hand: it counts as the first stitch.',
      'Hold the yarn as for the long-tail cast-on: the tail over your left thumb, the working yarn over your left index finger.',
      'Purl stitch: dip the needle tip under the index finger strand from the back, so that it sits between the two strands.',
      'Hook the thumb strand by passing over it, then in front of it, and come back out the same way, under the index finger strand: the purl stitch is on the needle.',
      'Knit stitch: dip the tip under the thumb strand from the front, so that it sits between the two strands.',
      'Hook the index finger strand by passing over it, then behind it, and come back out the same way, under the thumb strand: the knit stitch is on the needle.',
      'Repeat steps 4 to 7 until you reach the number of stitches required, always alternating purl and knit.',
      'Work 2 tubular rows, slipping purlwise with the yarn in front the stitches that face you as purl stitches; on row 1, if the first stitch faces you as a knit stitch, knit it normally, and knit all the other knit stitches through the back loop; on row 2, knit the knit stitches normally.',
      'Change to the ribbing needles and carry on in 1x1 rib.',
    ],
    tip: 'The knit stitches come off the cast-on turned on the needle: working them through the back loop on row 1 sets them the right way; only the first stitch, if it faces you as a knit stitch, is knitted normally. Cast on flat, and only join in the round after the 2 tubular rows.',
  },
  'kn-co-cable': {
    name: 'Cable cast-on',
    abbr: [],
    steps: [
      'Hold the needle with the stitches in your left hand, yarn at the back of the work.',
      'Insert the right needle between the first 2 stitches on the left needle, from front to back.',
      'Wrap the yarn around the right needle, as for a knit stitch.',
      'Pull the loop through to the front, between the 2 stitches.',
      'Slip this loop onto the left needle without twisting it: it is the new first stitch.',
      'Take out the right needle and pull the yarn gently to even out the stitch.',
      'Repeat steps 2 to 6 until you have added the number of stitches required.',
    ],
    tip: 'To start from an empty needle, make a slip knot, knit into it without dropping it and slip the new loop onto the left needle: you have your 2 starting stitches. Do not pull too tight, this cast-on is already firm.',
  },
  'kn-bo': {
    name: 'Basic bind-off (cast off)',
    abbr: ['BO'],
    steps: [
      'Work the first 2 stitches as they present themselves, knit or purl.',
      'Insert the left needle into the first stitch you worked, the one furthest from the tip of the right needle.',
      'Lift it over the second stitch and off the right needle: 1 stitch is bound off.',
      'Work the next stitch: you have 2 stitches on the right needle again.',
      'Repeat steps 2 to 4 until only 1 stitch is left on the right needle.',
      'Cut the yarn, leaving about 15 cm.',
      'Pass the end through the last stitch and pull to close it.',
    ],
    tip: 'Bind off loosely, with a larger needle if needed: a tight edge puckers. When you bind off a few stitches at the start of a row, the stitch left on the right needle counts as the first of the stitches that follow.',
  },
  'kn-bo-tubular': {
    name: 'Tubular bind-off (Italian bind-off)',
    abbr: [],
    steps: [
      'Cut the yarn, leaving 3 to 4 times the width of the edge, and thread it onto a tapestry needle.',
      'Check that the first stitch on the needle is a knit stitch: the bind-off starts with it.',
      'Insert the tapestry needle purlwise into this first stitch, pull the yarn through and leave it on the needle.',
      'Take the second stitch, a purl stitch, from the back of the work: the tapestry needle passes from back to front between the first 2 stitches, then goes knitwise into the purl stitch; pull the yarn through and leave it on the needle.',
      'Insert the tapestry needle knitwise into the first stitch, a knit stitch, and slip it off the needle without pulling the yarn through.',
      'Skip the purl stitch and insert the tapestry needle purlwise into the next knit stitch; pull the yarn through and leave it on the needle.',
      'Insert the tapestry needle purlwise into the first stitch, the skipped purl stitch, slip it off the needle and pull the yarn through.',
      'Repeat the move from step 4 on the next purl stitch.',
      'Repeat steps 5 to 8 until only 1 stitch is left on the needle, pulling the yarn just enough for each stitch to match the size of a knitted stitch.',
      'Pass the yarn purlwise through the last stitch, then weave it in.',
    ],
    tip: 'Also called the sewn tubular bind-off, it is meant for 1x1 rib only. For an even rounder edge, first work 2 tubular rows: knit the knit stitches and slip the purl stitches purlwise, with the yarn in front.',
  },
  'kn-knit': {
    name: 'Knit stitch',
    abbr: ['k'],
    steps: [
      'Hold the needle with the stitches in your left hand, yarn at the back of the work.',
      'Insert the right needle into the first stitch from front to back, left to right.',
      'Wrap the yarn around the right needle, from left to right.',
      'Pull that loop through the stitch toward the front.',
      'Slide the stitch off the left needle: the new stitch is now on the right needle.',
    ],
    tip: 'Do not pull the yarn too tight: a tight stitch is hard to knit on the next row.',
  },
  'kn-purl': {
    name: 'Purl stitch',
    abbr: ['p'],
    steps: [
      'Hold the needle with the stitches in your left hand, yarn at the front of the work.',
      'Insert the right needle into the first stitch from right to left, in front of the left needle.',
      'Wrap the yarn around the right needle: over the top toward the back, then down between the needles and back to the front.',
      'Push that loop back through the stitch.',
      'Slide the stitch off the left needle: the new stitch is now on the right needle.',
    ],
    tip: 'Keep the yarn at the front from one purl stitch to the next: if it goes over the needle between two stitches, it adds a stitch and leaves a hole.',
  },
  'kn-tbl': {
    name: 'Knit through the back loop (twisted stitch)',
    abbr: ['tbl', 'ktbl', 'k1 tbl'],
    steps: [
      'Keep the yarn at the back of the work, as for a knit stitch.',
      'Insert the right needle into the back loop of the first stitch, from right to left, behind the left needle.',
      'Wrap the yarn around the right needle, as for a knit stitch.',
      'Pull the loop through the stitch toward the front.',
      'Slide the stitch off the left needle: its base is crossed.',
    ],
    tip: 'To purl through the back loop, insert the needle into the back loop from left to right, from behind, then purl the stitch. If the base of the stitch is not crossed, you went into the front loop.',
  },
  'kn-slip': {
    name: 'Slip a stitch',
    abbr: ['sl', 'wyib', 'wyif'],
    steps: [
      'Put the yarn on the side the pattern asks for, at the front or the back of the work; if it does not say, keep it on the wrong side.',
      'Insert the right needle into the stitch from right to left, as if to purl.',
      'Move the stitch onto the right needle without working it.',
      'Work the next stitch without pulling on the yarn that runs in front of or behind the slipped stitch.',
    ],
    tip: 'Unless told otherwise, slip purlwise: the stitch keeps its orientation. Slip knitwise, inserting from left to right, only when the pattern says so, as in decreases.',
  },
  'kn-yo': {
    name: 'Yarn over',
    abbr: ['yo'],
    steps: [
      'If the yarn is at the back of the work, bring it to the front between the two needles.',
      'If the next stitch is a knit stitch, knit it: the yarn goes over the right needle and forms the yarn over.',
      'If it is a purl stitch, first take the yarn once all the way around the right needle: over the top to the back, then between the needles to the front.',
      'Then purl the stitch.',
      'On the next row, work the yarn over like an ordinary stitch: it adds 1 stitch and leaves a small hole.',
    ],
    tip: 'Work the yarn over through its front loop: through the back loop, it twists and the hole closes up. A yarn over is easy to lose, so count your stitches at the end of the row.',
  },
  'kn-k2tog': {
    name: 'Knit 2 together',
    abbr: ['k2tog'],
    steps: [
      'Keep the yarn at the back of the work, as for a knit stitch.',
      'Insert the right needle into the next 2 stitches at once, from front to back.',
      'Wrap the yarn around the right needle.',
      'Pull the loop through both stitches.',
      'Slide both stitches off the left needle: they now form one stitch, leaning to the right.',
    ],
    tip: 'Your stitch count drops by 1. Count at the end of the row to make sure you land on the right number.',
  },
  'kn-p2tog': {
    name: 'Purl 2 together',
    abbr: ['p2tog'],
    steps: [
      'Keep the yarn at the front of the work, as for a purl stitch.',
      'Insert the right needle into the next 2 stitches at once, from right to left, as if to purl.',
      'Wrap the yarn around the right needle: over the top toward the back, then down between the needles and back to the front.',
      'Push the loop back through both stitches.',
      'Slide both stitches off the left needle: they now form one stitch.',
    ],
    tip: 'Seen from the right side, this decrease leans to the right, like knit 2 together: it is its twin for wrong-side rows.',
  },
  'kn-skp': {
    name: 'Slip, knit, pass over',
    abbr: ['skp', 'skpo'],
    steps: [
      'Slip 1 stitch knitwise onto the right needle, without working it.',
      'Knit the next stitch.',
      'Insert the left needle into the slipped stitch, from the front.',
      'Lift it over the knitted stitch and off the right needle: 2 stitches have become one, leaning to the left.',
    ],
    tip: 'This is not the ssk, described separately: here one stitch is passed over the other, and the decrease is a little looser. Some patterns use one name for either move: check their key.',
  },
  'kn-ssk': {
    name: 'Slip, slip, knit (ssk)',
    abbr: ['ssk'],
    steps: [
      'Slip 1 stitch knitwise onto the right needle.',
      'Slip the next stitch the same way, separately from the first.',
      'Insert the left needle into the front of both slipped stitches, from left to right: the right needle stays behind.',
      'Wrap the yarn around the right needle, as for a knit stitch.',
      'Pull the loop through both stitches and slide them off the left needle: they now form one stitch, leaning to the left.',
    ],
    tip: 'This amounts to knitting 2 stitches together through the back loop after slipping them knitwise one at a time. It is not the slip, knit, pass over, described separately: no stitch is passed over, and the decrease lies flatter.',
  },
  'kn-cdd': {
    name: 'Centred double decrease',
    abbr: ['cdd', 's2kp'],
    steps: [
      'Slip 2 stitches together onto the right needle, inserting into both at once as if to knit them together.',
      'Knit the next stitch.',
      'Insert the left needle into the 2 slipped stitches, from the front.',
      'Lift them together over the knitted stitch and off the right needle: 3 stitches have become one, and the middle one stays straight, on top.',
    ],
    tip: 'Slip the 2 stitches together, not one at a time, or the middle stitch will not stay on top. Do not confuse it with sk2p (slip 1, knit 2 together, pass the slipped stitch over), which leans to the left.',
  },
  'kn-m1': {
    name: 'Make one left and make one right',
    abbr: ['m1', 'm1l', 'm1r'],
    steps: [
      'Find the horizontal strand running between the last stitch on the right needle and the first one on the left needle.',
      'For make one left, lift this strand with the left needle, from front to back.',
      'Knit it through the back loop: the new stitch is twisted and leans to the left.',
      'For make one right, lift the strand with the left needle, from back to front.',
      'Knit it through the front loop: the new stitch is twisted and leans to the right.',
    ],
    tip: 'If a hole appears, the strand did not twist: you knitted it through the wrong loop. Each increase adds 1 stitch.',
  },
  'kn-kfb': {
    name: 'Knit front and back',
    abbr: ['kfb'],
    steps: [
      'Knit the next stitch without sliding it off the left needle.',
      'Insert the right needle into the back loop of that same stitch, from right to left, behind the left needle.',
      'Wrap the yarn around the right needle and pull the loop through the stitch.',
      'Slide the stitch off the left needle: you have 2 stitches on the right needle.',
    ],
    tip: 'The second stitch leaves a small horizontal bar at its base: that is normal, and it is how you spot the increase. Each increase adds 1 stitch.',
  },
  'kn-stockinette': {
    name: 'Stockinette stitch (US) / stocking stitch (UK)',
    abbr: ['St st'],
    steps: [
      'Cast on the number of stitches required.',
      'Knit every stitch: this is a right-side row.',
      'Turn the work.',
      'Purl every stitch: this is a wrong-side row.',
      'Turn the work.',
      'Repeat steps 2 to 5 until the piece reaches the required length.',
      'In the round, knit every round and never turn the work.',
    ],
    tip: 'The right side shows columns of Vs, the wrong side rows of little bumps; when the bumps are meant to show, patterns call it reverse stockinette. Stockinette curls at the edges: a border of ribbing or garter stitch keeps it flat.',
  },
  'kn-garter': {
    name: 'Garter stitch',
    abbr: ['g st'],
    steps: [
      'Cast on the number of stitches required.',
      'Knit every stitch.',
      'Turn the work.',
      'Repeat steps 2 and 3: worked flat, every row is knitted.',
      'In the round, knit one round.',
      'Purl the next round.',
      'Repeat steps 5 and 6 until the piece reaches the required length.',
    ],
    tip: 'Count the raised ridges rather than the rows: each ridge stands for 2 rows. Garter stitch lies flat and looks the same on both sides.',
  },
  'kn-rib': {
    name: 'Ribbing (1x1 and 2x2)',
    abbr: [],
    steps: [
      'Cast on an odd number of stitches for 1x1 rib, or a multiple of 4 plus 2 for 2x2 rib: both edges will then match.',
      '1x1 rib: alternate 1 knit stitch and 1 purl stitch up to the last stitch, and knit that one.',
      '2x2 rib: alternate 2 knit stitches and 2 purl stitches up to the last 2 stitches, and knit those.',
      'At each change, move the yarn between the two needles: to the front before a purl stitch, to the back before a knit stitch.',
      'Turn the work.',
      'Work each stitch the way it faces you: knit the ones that show a V, purl the ones that show a bump.',
      'Repeat steps 5 and 6 until the ribbing reaches the required length.',
      'In the round, cast on an even number of stitches for 1x1 rib, a multiple of 4 for 2x2 rib, and work every round like the first.',
    ],
    tip: 'An extra stitch next to a small hole means the yarn went over the needle instead of between the two: it made a yarn over. On the right side, the columns of Vs should stay neatly lined up.',
  },
  'kn-seed': {
    name: 'Seed stitch (US) / moss stitch (UK)',
    abbr: [],
    steps: [
      'Cast on an odd number of stitches.',
      'Knit 1 stitch.',
      'Bring the yarn to the front between the needles and purl 1 stitch.',
      'Take the yarn to the back between the needles.',
      'Repeat steps 2 to 4 up to the last stitch, and knit that one.',
      'Turn the work and work every row the same way: it starts and ends with 1 knit stitch.',
      'Check as you go: a stitch that shows a V gets purled, a stitch that shows a bump gets knitted.',
      'In the round, on an even number of stitches, apply the same rule on every round.',
    ],
    tip: 'If columns appear, you are working the stitches the way they face you, which gives 1x1 rib. In US patterns, moss stitch is a different pattern whose knits and purls only shift every 2 rows.',
  },
  'kn-cable': {
    name: 'Cable (4 stitches, with a cable needle)',
    abbr: ['C4B', 'C4F'],
    steps: [
      'On a right-side row, work up to the 4 cable stitches.',
      'Slip the first 2 cable stitches purlwise onto the cable needle.',
      'Let the cable needle hang at the back of the work: its stitches will pass underneath, and the cable will cross to the right.',
      'Knit the next 2 stitches from the left needle, snugging up the first one a little.',
      'Knit the 2 stitches from the cable needle, starting with the one slipped first.',
      'For a cable that crosses to the left, make the same moves with the cable needle held at the front of the work in step 3.',
      'Between two crossings, work the stitches the way they face you, and cross again on the row given by the pattern.',
    ],
    tip: 'If the cable twists the wrong way, check where the cable needle was: at the back it crosses right (C4B), at the front it crosses left (C4F). Slip the stitches without twisting them, or they stay crossed at the base.',
  },
  'kn-short-rows-german': {
    name: 'German short rows',
    abbr: ['DS', 'MDS'],
    steps: [
      'Work up to the turning point given by the pattern.',
      'Turn the work: the unworked stitches wait on the right needle.',
      'Bring the yarn to the front of the work, if it is not there already.',
      'Slip the first stitch purlwise onto the right needle.',
      'Pull the yarn up and then back, over the right needle, until the slipped stitch shows two legs on the needle: this is the double stitch.',
      'Keep the yarn taut; if the next stitch is to be purled, bring the yarn to the front again, between the needles.',
      'Work to the next turning point and repeat steps 2 to 6.',
      'When you reach a double stitch, insert the needle into both of its legs at once.',
      'Work them together as a single stitch, knitting or purling as the row requires.',
    ],
    tip: 'A double stitch counts as 1 stitch, not 2. Pull the yarn firmly in step 5: too loose, it leaves a hole at the turn.',
  },
  'kn-pick-up': {
    name: 'Picking up stitches',
    abbr: ['PU', 'PUK'],
    steps: [
      'Hold the work right side facing you, the edge to pick up along the top, and start at the right-hand corner.',
      'On a cast-on or bound-off edge, insert the right needle from front to back into the middle of the V of the stitch that runs along the edge.',
      'On a side edge, insert it from front to back between the edge stitch and its neighbour, one full stitch in from the edge.',
      'Wrap the working yarn around the right needle, as for a knit stitch.',
      'Pull the loop through to the front: 1 stitch is picked up and knitted onto the right needle.',
      'On a cast-on or bound-off edge, repeat in every stitch: 1 stitch picked up for each stitch of the edge.',
      'On a stockinette side edge, pick up 3 stitches for every 4 rows by skipping 1 row in 4: a stitch is wider than a row is tall.',
      'On a garter stitch side edge, pick up 1 stitch per ridge.',
    ],
    tip: 'To spread the stitches evenly, divide the edge into equal parts with markers and pick up the same number of stitches in each. A hole means a stitch was picked up too close to the edge, in half a stitch.',
  },
  'kn-kitchener': {
    name: 'Kitchener stitch (grafting)',
    abbr: [],
    steps: [
      'Divide the stitches between two needles, the same number on each, and hold them parallel, wrong sides together, tips pointing to the right.',
      'Cut the yarn, leaving 3 to 4 times the width to graft, thread it onto a tapestry needle and check that it comes from the back needle.',
      'Setup: insert the tapestry needle purlwise into the first stitch on the front needle, pull the yarn through and leave the stitch on the needle.',
      'Insert it knitwise into the first stitch on the back needle, pull the yarn through and leave the stitch on the needle.',
      'Front needle: insert the tapestry needle knitwise into the first stitch and slip it off the needle without pulling the yarn through.',
      'Insert it purlwise into the next stitch on the front needle; pull the yarn through and leave that stitch on the needle.',
      'Back needle: insert the tapestry needle purlwise into the first stitch and slip it off the needle without pulling the yarn through.',
      'Insert it knitwise into the next stitch on the back needle; pull the yarn through and leave that stitch on the needle.',
      'Repeat steps 5 to 8 until one stitch is left on each needle, pulling the yarn just enough for each stitch to match the size of a knitted stitch.',
      'Finish with the front stitch, taken knitwise and slipped off, then the back stitch, taken purlwise and slipped off; weave in the end.',
    ],
    tip: 'Always complete the whole series of steps 5 to 8 before putting the work down: otherwise you may pick up again at the wrong step. If the seam shows, adjust the tension stitch by stitch so that it looks like the neighbouring row.',
  },
}
