// Fichas del memorándum de puntos en español. Redactadas para Rowtine: sin reutilizar
// textos ajenos. Claves = identificadores de catalog.js.
export const STITCH_MEMO_ES = {
  'cr-ch': {
    name: 'Cadeneta (con nudo corredizo)',
    abbr: ['cad'],
    steps: [
      'Forma un lazo con la hebra, a unos 10 cm del extremo.',
      'Saca una lazada de la hebra del ovillo a través de ese lazo: es el nudo corredizo.',
      'Coloca el nudo corredizo en el ganchillo y ajústalo sin apretar demasiado.',
      'Haz una lazada.',
      'Pásala por la lazada del ganchillo: has hecho 1 cadeneta.',
      'Repite la lazada y el paso de la hebra hasta tener el número de cadenetas indicado.',
    ],
    tip: 'No cuentes el nudo corredizo ni la lazada del ganchillo: cuenta las pequeñas uves del derecho de la cadeneta.',
  },
  'cr-slst': {
    name: 'Punto deslizado',
    abbr: ['pd', 'pr'],
    steps: [
      'Introduce el ganchillo en el punto siguiente, bajo las dos hebras.',
      'Haz una lazada.',
      'Pásala a la vez por el punto y por la lazada del ganchillo, en un solo gesto.',
    ],
    tip: 'El punto deslizado casi no añade altura: sirve para cerrar una vuelta o para desplazarte por la fila. Hazlo flojo, o te costará entrar en él en la vuelta siguiente.',
  },
  'cr-sc': {
    name: 'Punto bajo',
    abbr: ['pb', 'mp'],
    steps: [
      'Introduce el ganchillo en el punto siguiente, bajo las dos hebras.',
      'Haz una lazada y tira de ella a través del punto: ahora hay 2 lazadas en el ganchillo.',
      'Haz otra lazada.',
      'Pásala por las 2 lazadas de una sola vez.',
    ],
    tip: 'Cuenta los puntos al final de la vuelta: el punto bajo es corto y un punto olvidado se nota enseguida en la vuelta siguiente.',
  },
  'cr-hdc': {
    name: 'Punto medio alto',
    abbr: ['pma', 'mpa'],
    steps: [
      'Haz una lazada.',
      'Introduce el ganchillo en el punto siguiente, bajo las dos hebras.',
      'Haz una lazada y tira de ella a través del punto: ahora hay 3 lazadas en el ganchillo.',
      'Haz otra lazada.',
      'Pásala por las 3 lazadas de una sola vez.',
    ],
    tip: 'Al empezar la fila, las cadenetas de giro son 2. Según el patrón, cuentan o no como el primer punto medio alto: compruébalo antes de introducir el ganchillo.',
  },
  'cr-dc': {
    name: 'Punto alto (vareta)',
    abbr: ['pa'],
    steps: [
      'Haz una lazada.',
      'Introduce el ganchillo en el punto siguiente, bajo las dos hebras.',
      'Haz una lazada y tira de ella a través del punto: ahora hay 3 lazadas en el ganchillo.',
      'Haz una lazada y pásala por las 2 primeras lazadas: quedan 2.',
      'Haz una lazada y pásala por las 2 últimas lazadas.',
    ],
    tip: 'Las 3 cadenetas de giro suelen contar como el primer punto alto: haz entonces el siguiente en el segundo punto de la fila, o la labor se ensanchará.',
  },
  'cr-tr': {
    name: 'Punto alto doble',
    abbr: ['pad'],
    steps: [
      'Haz dos lazadas.',
      'Introduce el ganchillo en el punto siguiente, bajo las dos hebras.',
      'Haz una lazada y tira de ella a través del punto: ahora hay 4 lazadas en el ganchillo.',
      'Haz una lazada y pásala por 2 lazadas: quedan 3.',
      'Haz una lazada y pásala por 2 lazadas: quedan 2.',
      'Haz una lazada y pásala por las 2 últimas lazadas.',
    ],
    tip: 'Cierras las lazadas de 2 en 2, tres veces seguidas. Al empezar la fila, las cadenetas de giro son 4.',
  },
  'cr-inc': {
    name: 'Aumento',
    abbr: ['aum'],
    steps: [
      'Haz un punto bajo en el punto siguiente.',
      'Introduce otra vez el ganchillo en ese mismo punto.',
      'Haz un segundo punto bajo: de un solo punto de la base salen ahora 2.',
    ],
    tip: 'Cada aumento añade 1 punto, y el gesto es el mismo con puntos altos. En redondo, cambia de sitio los aumentos de una vuelta a otra, o el círculo saldrá con esquinas.',
  },
  'cr-dec': {
    name: 'Disminución (2 puntos bajos juntos)',
    abbr: ['dism'],
    steps: [
      'Introduce el ganchillo en el punto siguiente.',
      'Haz una lazada y tira de ella a través del punto: ahora hay 2 lazadas en el ganchillo.',
      'Introduce el ganchillo en el punto que sigue.',
      'Haz una lazada y tira de ella a través del punto: ahora hay 3 lazadas en el ganchillo.',
      'Haz otra lazada.',
      'Pásala por las 3 lazadas de una sola vez: 2 puntos se han convertido en 1.',
    ],
    tip: 'En amigurumi, la disminución invisible deja menos hueco: introduce el ganchillo solo por las hebras delanteras de los 2 puntos a la vez y termina como un punto bajo.',
  },
  'cr-magic-ring': {
    name: 'Anillo mágico',
    abbr: ['AM'],
    steps: [
      'Enrolla la hebra alrededor de dos dedos para formar un lazo, con el extremo cruzado por encima de la hebra del ovillo.',
      'Pasa el ganchillo por el lazo, atrapa la hebra del ovillo y sácala a través.',
      'Haz 1 cadeneta para fijarlo: no cuenta como punto.',
      'Teje dentro del anillo los puntos bajos indicados, a menudo 6, pasando por debajo del lazo y del extremo a la vez.',
      'Tira del extremo para cerrar el anillo.',
      'Cierra la vuelta con un punto deslizado en el primer punto bajo, o sigue en espiral.',
    ],
    tip: 'Remata el extremo cambiando de dirección varias veces: es lo que mantiene el anillo cerrado, y si se suelta, el centro vuelve a abrirse.',
  },
  'cr-rounds': {
    name: 'Tejer en filas y en redondo',
    abbr: [],
    steps: [
      'En filas, haz al final de la fila las cadenetas de giro: 1 para punto bajo, 2 para punto medio alto, 3 para punto alto.',
      'Gira la labor y empieza la fila siguiente.',
      'En vueltas cerradas, termina cada vuelta con un punto deslizado en el primer punto de la vuelta.',
      'Haz las cadenetas de altura de la nueva vuelta y sigue sin girar la labor.',
      'En espiral, no cierres la vuelta: sigue directamente en el primer punto de la vuelta anterior.',
      'Coloca un marcador en el primer punto de cada vuelta y súbelo en cada vuelta nueva.',
    ],
    tip: 'Según el patrón, las cadenetas de giro cuentan o no como un punto: vuelve a leer la indicación, es la causa más frecuente de una fila que gana o pierde un punto.',
  },
  'cr-flo-blo': {
    name: 'Solo bucle delantero / solo bucle trasero',
    abbr: ['BD', 'BT'],
    steps: [
      'Mira la parte de arriba del punto: forma una V tumbada, con dos hebras.',
      'Localiza el bucle delantero, la hebra más cercana a ti, y el bucle trasero, la hebra más alejada.',
      'Para tejer en la hebra delantera, introduce el ganchillo solo bajo esa hebra.',
      'Para tejer en la hebra trasera, pasa el ganchillo entre las dos hebras y solo bajo la trasera.',
      'Termina el punto como de costumbre.',
    ],
    tip: 'Delantera y trasera se leen respecto a ti, tal como sujetas la labor, no respecto al derecho del tejido. La hebra que queda libre forma una línea en relieve.',
  },
  'cr-color-change': {
    name: 'Cambio de color',
    abbr: [],
    steps: [
      'Empieza el último punto con el color antiguo y detente antes de su última lazada.',
      'Suelta el color antiguo, dejando unos 10 cm de hebra si lo cortas.',
      'Toma el color nuevo, dejando un extremo de unos 10 cm.',
      'Haz la última lazada con el color nuevo y pásala: el punto está terminado.',
      'Sigue tejiendo con el color nuevo.',
      'Al final, remata los dos extremos, cada uno en puntos de su color.',
    ],
    tip: 'En vueltas cerradas, cambia de color en el punto deslizado de cierre: hazlo con el color nuevo y la unión se notará menos.',
  },
  'cr-shell': {
    name: 'Punto abanico (concha)',
    abbr: [],
    steps: [
      'Haz un punto bajo en el primer punto.',
      'Salta el número de puntos que indica el patrón, a menudo 2.',
      'Teje en el punto siguiente los puntos altos indicados, a menudo 5.',
      'Salta otra vez el mismo número de puntos.',
      'Haz un punto bajo en el punto siguiente para fijar el abanico.',
      'Repite los pasos 2 a 5 hasta el final de la fila.',
    ],
    tip: 'Con 5 puntos altos y 2 puntos saltados a cada lado, cada motivo ocupa 6 puntos: la fila de base necesita un múltiplo de 6 puntos más 1, o el último abanico quedará torcido.',
  },
  'cr-picot': {
    name: 'Piquillo (picot)',
    abbr: [],
    steps: [
      'Haz 3 cadenetas, o las que indique el patrón.',
      'Introduce el ganchillo en la primera de esas cadenetas, la tercera desde el ganchillo.',
      'Haz una lazada.',
      'Pásala a la vez por la cadeneta y por la lazada del ganchillo: el piquillo queda cerrado con un punto deslizado.',
    ],
    tip: 'Algunos patrones cierran el piquillo en la parte de arriba del punto anterior en lugar de en la cadeneta: sigue la indicación, porque la base del piquillo no queda en el mismo sitio.',
  },
  'cr-popcorn': {
    name: 'Punto palomita (popcorn)',
    abbr: [],
    steps: [
      'Teje 5 puntos altos en el mismo punto, o los que indique el patrón.',
      'Saca el ganchillo de la lazada y agrándala un poco para que no se deshaga.',
      'Introduce el ganchillo de delante hacia atrás en la parte de arriba del primero de los 5 puntos altos.',
      'Recoge con el ganchillo la lazada que dejaste en espera.',
      'Pásala por la parte de arriba del primer punto alto: el grupo se cierra y sobresale hacia delante.',
      'Haz 1 cadeneta para fijar la palomita.',
    ],
    tip: 'La palomita sobresale hacia el lado desde el que introduces el ganchillo: de delante hacia atrás, sale hacia ti. No la confundas con el punto puff, cuyas lazadas se cierran juntas.',
  },
  'cr-puff': {
    name: 'Punto puff',
    abbr: [],
    steps: [
      'Haz una lazada e introduce el ganchillo en el punto.',
      'Haz una lazada y saca una lazada larga, más o menos a la altura de un punto medio alto.',
      'Repite estos dos pasos 3 veces más en el mismo punto: ahora hay 9 lazadas en el ganchillo.',
      'Haz una lazada y pásala por las 9 lazadas de una sola vez.',
      'Haz 1 cadeneta para cerrar el punto.',
    ],
    tip: 'Si las lazadas no pasan, son demasiado cortas o están demasiado apretadas: dales a todas la misma altura y sujétalas contra el ganchillo con el índice.',
  },
  'cr-post': {
    name: 'Punto alto en relieve por delante y por detrás',
    abbr: [],
    steps: [
      'Haz una lazada.',
      'Para el relieve por delante, introduce el ganchillo de delante hacia atrás por un lado del tallo del punto alto de la vuelta anterior y sácalo hacia delante por el otro lado: el ganchillo pasa por detrás del tallo.',
      'Haz una lazada y sácala rodeando el tallo: ahora hay 3 lazadas en el ganchillo.',
      'Haz una lazada y pásala por las 2 primeras lazadas.',
      'Haz una lazada y pásala por las 2 últimas lazadas.',
      'Para el relieve por detrás, tras la lazada, introduce el ganchillo de detrás hacia delante por un lado del tallo y sácalo hacia atrás por el otro lado: el ganchillo pasa por delante del tallo.',
      'Termina el punto como en el relieve por delante, con los pasos 3 a 5.',
    ],
    tip: 'No tejas en la parte de arriba del punto cuyo tallo has rodeado: queda escondida detrás del relieve, y saltarla mantiene el número de puntos.',
  },
  'kn-co-long-tail': {
    name: 'Montaje de cola larga',
    abbr: [],
    steps: [
      'Mide un tramo de hebra libre para la cola: calcula unos 2 a 3 cm por punto que vayas a montar, según el grosor de la lana.',
      'Haz un nudo corredizo en ese punto y colócalo en la aguja: cuenta como el primer punto.',
      'Sujeta la aguja con la mano derecha, pasa la cola alrededor del pulgar izquierdo y la hebra del ovillo por el índice izquierdo, con los dos extremos sujetos en la palma.',
      'Pasa la punta de la aguja de abajo arriba por el lazo del pulgar, bajo la hebra delantera.',
      'Atrapa con la punta la hebra del índice, pasando por encima de ella.',
      'Saca esa hebra a través del lazo del pulgar.',
      'Suelta el lazo del pulgar y separa el pulgar bajo la cola para ajustar el punto en la aguja.',
      'Repite los pasos 4 a 7 hasta tener el número de puntos indicado.',
    ],
    tip: 'Si la cola se acaba antes del final, vuelve a empezar con una cola más larga en lugar de añadir hebra. Ajusta los puntos sin estrangular la aguja: deben poder deslizarse.',
  },
  'kn-co-tubular': {
    name: 'Montaje tubular (italiano)',
    abbr: [],
    steps: [
      'Usa una aguja 1 o 2 números más fina que para el elástico y deja una cola de 3 a 4 veces el ancho que vas a montar.',
      'Haz un nudo corredizo y colócalo en la aguja, sujeta con la mano derecha: cuenta como el primer punto.',
      'Sujeta las hebras como para el montaje de cola larga: la cola en el pulgar izquierdo y la hebra del ovillo en el índice izquierdo.',
      'Punto revés: mete la punta de la aguja bajo la hebra del índice, viniendo desde atrás, para dejarla entre las dos hebras.',
      'Engancha la hebra del pulgar pasando por encima y luego por delante de ella, y sal por el mismo camino, bajo la hebra del índice: el punto revés está en la aguja.',
      'Punto derecho: mete la punta bajo la hebra del pulgar, viniendo desde delante, para dejarla entre las dos hebras.',
      'Engancha la hebra del índice pasando por encima y luego por detrás de ella, y sal por el mismo camino, bajo la hebra del pulgar: el punto derecho está en la aguja.',
      'Repite los pasos 4 a 7 hasta tener el número de puntos indicado, alternando siempre revés y derecho.',
      'Teje 2 vueltas tubulares deslizando como para tejer del revés, con la hebra delante, los puntos que se presentan al revés; en la 1.ª vuelta, si el primer punto se presenta al derecho, téjelo normalmente, y teje todos los demás puntos derechos por la hebra trasera; en la 2.ª vuelta, teje los puntos derechos normalmente.',
      'Cambia a las agujas del elástico y sigue en elástico 1x1.',
    ],
    tip: 'Los puntos derechos salen del montaje girados en la aguja: tejerlos por la hebra trasera en la 1.ª vuelta los pone en su sentido; solo el primero, si se presenta al derecho, se teje normalmente. Monta en plano y no cierres en redondo hasta después de las 2 vueltas tubulares.',
  },
  'kn-co-cable': {
    name: 'Montaje de cable (entre puntos)',
    abbr: [],
    steps: [
      'Sujeta con la mano izquierda la aguja con los puntos, con la hebra por detrás de la labor.',
      'Introduce la aguja derecha entre los 2 primeros puntos de la aguja izquierda, de delante hacia atrás.',
      'Pasa la hebra alrededor de la aguja derecha, como para un punto derecho.',
      'Saca la lazada hacia delante, entre los 2 puntos.',
      'Pasa esa lazada a la aguja izquierda sin retorcerla: es el nuevo primer punto.',
      'Retira la aguja derecha y tira suavemente de la hebra para ajustar el punto.',
      'Repite los pasos 2 a 6 hasta añadir el número de puntos indicado.',
    ],
    tip: 'Para empezar con la aguja vacía, haz un nudo corredizo, téjelo del derecho sin soltarlo y pasa la nueva lazada a la aguja izquierda: ya tienes los 2 puntos de partida. No aprietes demasiado, este montaje ya es firme.',
  },
  'kn-bo': {
    name: 'Cierre clásico de puntos',
    abbr: [],
    steps: [
      'Teje los 2 primeros puntos como se presenten, del derecho o del revés.',
      'Introduce la aguja izquierda en el primer punto tejido, el más alejado de la punta de la aguja derecha.',
      'Pásalo por encima del segundo punto y fuera de la aguja derecha: has cerrado 1 punto.',
      'Teje el punto siguiente: vuelves a tener 2 puntos en la aguja derecha.',
      'Repite los pasos 2 a 4 hasta que solo quede 1 punto en la aguja derecha.',
      'Corta la hebra dejando unos 15 cm.',
      'Pasa el extremo por el último punto y tira para cerrarlo.',
    ],
    tip: 'Cierra sin apretar, con una aguja más gruesa si hace falta: un borde demasiado tenso frunce. Cuando cierras unos pocos puntos al principio de la vuelta, el punto que queda en la aguja derecha cuenta como el primero de los siguientes.',
  },
  'kn-bo-tubular': {
    name: 'Cierre tubular (italiano)',
    abbr: [],
    steps: [
      'Corta la hebra dejando 3 a 4 veces el ancho del borde y enhébrala en una aguja lanera.',
      'Comprueba que el primer punto de la aguja es un punto derecho: el cierre empieza por él.',
      'Introduce la aguja lanera en ese primer punto como para tejerlo del revés, pasa la hebra y déjalo en la aguja.',
      'Toma el segundo punto, un punto revés, por detrás de la labor: la aguja lanera pasa de atrás hacia delante entre los 2 primeros puntos y entra en el punto revés como para tejerlo del derecho; pasa la hebra y déjalo en la aguja.',
      'Introduce la aguja lanera en el primer punto, un punto derecho, como para tejerlo del derecho, y sácalo de la aguja sin pasar la hebra.',
      'Salta el punto revés e introduce la aguja lanera en el siguiente punto derecho como para tejerlo del revés; pasa la hebra y déjalo en la aguja.',
      'Introduce la aguja lanera en el primer punto, el punto revés saltado, como para tejerlo del revés, sácalo de la aguja y pasa la hebra.',
      'Repite el gesto del paso 4 en el siguiente punto revés.',
      'Repite los pasos 5 a 8 hasta que solo quede 1 punto en la aguja, tirando de la hebra solo lo justo para que cada puntada tenga el tamaño de un punto.',
      'Pasa la hebra por el último punto como para tejerlo del revés y remátala.',
    ],
    tip: 'Este cierre está pensado para el elástico 1x1. Para un borde aún más redondeado, teje antes 2 vueltas: los puntos derechos del derecho y los puntos revés deslizados como para tejerlos del revés, con la hebra delante.',
  },
  'kn-knit': {
    name: 'Punto derecho',
    abbr: ['d', 'der', 'pd'],
    steps: [
      'Sujeta con la mano izquierda la aguja con los puntos, con la hebra por detrás de la labor.',
      'Introduce la aguja derecha en el primer punto, de delante hacia atrás, de izquierda a derecha.',
      'Pasa la hebra alrededor de la aguja derecha, de izquierda a derecha.',
      'Saca esa lazada hacia delante a través del punto.',
      'Deja caer el punto de la aguja izquierda: el punto nuevo queda en la aguja derecha.',
    ],
    tip: 'No tenses demasiado la hebra: un punto muy apretado es difícil de tejer en la vuelta siguiente.',
  },
  'kn-purl': {
    name: 'Punto revés',
    abbr: ['r', 'rev', 'pr'],
    steps: [
      'Sujeta con la mano izquierda la aguja con los puntos, con la hebra por delante de la labor.',
      'Introduce la aguja derecha en el primer punto, de derecha a izquierda, por delante de la aguja izquierda.',
      'Pasa la hebra por encima de la aguja derecha, de delante hacia atrás, y vuelve a traerla hacia delante entre las dos agujas.',
      'Saca esa lazada hacia atrás a través del punto.',
      'Deja caer el punto de la aguja izquierda: el punto nuevo queda en la aguja derecha.',
    ],
    tip: 'Mantén la hebra delante de un punto revés al siguiente: si pasa por encima de la aguja entre dos puntos, añade un punto y deja un agujero.',
  },
  'kn-tbl': {
    name: 'Punto derecho retorcido',
    abbr: [],
    steps: [
      'Deja la hebra por detrás de la labor, como para un punto derecho.',
      'Introduce la aguja derecha en la hebra trasera del primer punto, de derecha a izquierda, por detrás de la aguja izquierda.',
      'Pasa la hebra alrededor de la aguja derecha, como para un punto derecho.',
      'Saca la lazada hacia delante a través del punto.',
      'Deja caer el punto de la aguja izquierda: su base queda cruzada.',
    ],
    tip: 'Al revés, introduce la aguja en la hebra trasera de izquierda a derecha, por detrás, y teje el punto del revés. Si la base del punto no queda cruzada, has entrado por la hebra delantera.',
  },
  'kn-slip': {
    name: 'Deslizar un punto',
    abbr: [],
    steps: [
      'Deja la hebra en el lado que pide el patrón, delante o detrás de la labor; si no dice nada, déjala en el lado del revés del tejido.',
      'Introduce la aguja derecha en el punto, de derecha a izquierda, como para tejerlo del revés.',
      'Pasa el punto a la aguja derecha sin tejerlo.',
      'Teje el punto siguiente sin tirar de la hebra que pasa por delante o por detrás del punto deslizado.',
    ],
    tip: 'Si no se indica otra cosa, desliza como para tejer del revés: el punto conserva su orientación. Desliza como para tejer del derecho, de izquierda a derecha, solo cuando el patrón lo pida, como en las disminuciones.',
  },
  'kn-yo': {
    name: 'Lazada',
    abbr: ['laz'],
    steps: [
      'Si la hebra está detrás de la labor, llévala hacia delante entre las dos agujas.',
      'Si el punto siguiente es un punto derecho, téjelo: la hebra pasa por encima de la aguja derecha y forma la lazada.',
      'Si es un punto revés, da primero con la hebra una vuelta completa a la aguja derecha: por encima hacia atrás y luego entre las agujas hacia delante.',
      'Teje entonces el punto revés.',
      'En la vuelta siguiente, teje la lazada como un punto normal: añade 1 punto y deja un pequeño agujero.',
    ],
    tip: 'Teje la lazada por la hebra delantera: por la trasera se retuerce y el agujero se cierra. Una lazada se pierde con facilidad, cuenta los puntos al final de la vuelta.',
  },
  'kn-k2tog': {
    name: '2 puntos juntos al derecho',
    abbr: ['2 p juntos der', '2 p juntos d'],
    steps: [
      'Deja la hebra por detrás de la labor, como para un punto derecho.',
      'Introduce la aguja derecha en los 2 puntos siguientes a la vez, de delante hacia atrás.',
      'Pasa la hebra alrededor de la aguja derecha.',
      'Saca la lazada a través de los 2 puntos.',
      'Deja caer los 2 puntos de la aguja izquierda: ahora forman uno solo, inclinado hacia la derecha.',
    ],
    tip: 'El número de puntos baja en 1. Cuéntalos al final de la vuelta para comprobar que la cuenta sale bien.',
  },
  'kn-p2tog': {
    name: '2 puntos juntos al revés',
    abbr: ['2 p juntos rev', '2 p juntos r'],
    steps: [
      'Deja la hebra por delante de la labor, como para un punto revés.',
      'Introduce la aguja derecha en los 2 puntos siguientes a la vez, de derecha a izquierda, como para tejerlos del revés.',
      'Pasa la hebra por encima de la aguja derecha, de delante hacia atrás, y vuelve a traerla hacia delante entre las dos agujas.',
      'Saca la lazada hacia atrás a través de los 2 puntos.',
      'Deja caer los 2 puntos de la aguja izquierda: ahora forman uno solo.',
    ],
    tip: 'Vista desde el derecho, esta disminución se inclina hacia la derecha, como 2 puntos juntos al derecho: es su pareja para las vueltas del revés.',
  },
  'kn-skp': {
    name: 'Surjete simple (deslizar, tejer, pasar por encima)',
    abbr: [],
    steps: [
      'Desliza 1 punto a la aguja derecha como para tejerlo del derecho, sin tejerlo.',
      'Teje el punto siguiente del derecho.',
      'Introduce la aguja izquierda en el punto deslizado, por delante.',
      'Pásalo por encima del punto tejido y fuera de la aguja derecha: 2 puntos se han convertido en 1, inclinado hacia la izquierda.',
    ],
    tip: 'No es el ssk, que se describe aparte: aquí un punto pasa por encima del otro, y la disminución queda algo más floja. Algunos patrones llaman «surjete simple» a cualquiera de los dos gestos: consulta su leyenda.',
  },
  'kn-ssk': {
    name: 'Deslizar, deslizar, tejer (ssk)',
    abbr: ['ssk'],
    steps: [
      'Desliza 1 punto a la aguja derecha como para tejerlo del derecho.',
      'Desliza del mismo modo el punto siguiente, por separado.',
      'Introduce la aguja izquierda en la hebra delantera de los 2 puntos deslizados, de izquierda a derecha: la aguja derecha queda detrás.',
      'Pasa la hebra alrededor de la aguja derecha, como para un punto derecho.',
      'Saca la lazada a través de los 2 puntos y déjalos caer de la aguja izquierda: ahora forman uno solo, inclinado hacia la izquierda.',
    ],
    tip: 'Equivale a tejer juntos por la hebra trasera 2 puntos deslizados de uno en uno como para tejerlos del derecho. No es el surjete simple, que se describe aparte: ningún punto pasa por encima de otro y la disminución queda más plana.',
  },
  'kn-cdd': {
    name: 'Disminución doble centrada',
    abbr: [],
    steps: [
      'Desliza 2 puntos juntos a la aguja derecha, introduciéndola en los dos a la vez como para tejerlos juntos del derecho.',
      'Teje el punto siguiente del derecho.',
      'Introduce la aguja izquierda en los 2 puntos deslizados, por delante.',
      'Pásalos juntos por encima del punto tejido y fuera de la aguja derecha: 3 puntos se han convertido en 1, y el del centro queda recto, encima.',
    ],
    tip: 'Desliza los 2 puntos juntos, no de uno en uno, o el punto del centro no quedará encima. No la confundas con la disminución doble no centrada (deslizar 1 punto, tejer 2 juntos, pasar el deslizado por encima), que se inclina hacia la izquierda.',
  },
  'kn-m1': {
    name: 'Aumento intercalado (a la izquierda y a la derecha)',
    abbr: [],
    steps: [
      'Localiza la hebra horizontal que une el último punto de la aguja derecha con el primero de la aguja izquierda.',
      'Para el aumento inclinado a la izquierda, levanta esa hebra con la aguja izquierda, de delante hacia atrás.',
      'Téjela del derecho por la hebra trasera: el punto nuevo queda cruzado e inclinado hacia la izquierda.',
      'Para el aumento inclinado a la derecha, levanta la hebra con la aguja izquierda, de detrás hacia delante.',
      'Téjela del derecho por la hebra delantera: el punto nuevo queda cruzado e inclinado hacia la derecha.',
    ],
    tip: 'Si aparece un agujero, la hebra no se ha cruzado: la has tejido por el lado equivocado. Cada aumento añade 1 punto.',
  },
  'kn-kfb': {
    name: 'Aumento por la hebra delantera y trasera',
    abbr: [],
    steps: [
      'Teje del derecho el punto siguiente, sin dejarlo caer de la aguja izquierda.',
      'Introduce la aguja derecha en la hebra trasera de ese mismo punto, de derecha a izquierda, por detrás de la aguja izquierda.',
      'Pasa la hebra alrededor de la aguja derecha y saca la lazada a través del punto.',
      'Deja caer el punto de la aguja izquierda: tienes 2 puntos en la aguja derecha.',
    ],
    tip: 'El segundo punto deja una pequeña barra horizontal en su base: es normal, y así reconoces el aumento. Cada aumento añade 1 punto.',
  },
  'kn-stockinette': {
    name: 'Punto jersey (punto de media)',
    abbr: [],
    steps: [
      'Monta el número de puntos indicado.',
      'Teje todos los puntos del derecho: es una vuelta del derecho.',
      'Gira la labor.',
      'Teje todos los puntos del revés: es una vuelta del revés.',
      'Gira la labor.',
      'Repite los pasos 2 a 5 hasta la altura indicada.',
      'En redondo, teje todas las vueltas del derecho, sin girar nunca la labor.',
    ],
    tip: 'El derecho muestra columnas de V y el revés filas de pequeños nudos; cuando es ese lado el que se ve, el patrón habla de jersey revés. El punto jersey se enrolla en los bordes: un remate de elástico o de punto bobo lo mantiene plano.',
  },
  'kn-garter': {
    name: 'Punto bobo (punto Santa Clara)',
    abbr: [],
    steps: [
      'Monta el número de puntos indicado.',
      'Teje todos los puntos del derecho.',
      'Gira la labor.',
      'Repite los pasos 2 y 3: en plano, todas las vueltas se tejen del derecho.',
      'En redondo, teje una vuelta del derecho.',
      'Teje la vuelta siguiente del revés.',
      'Repite los pasos 5 y 6 hasta la altura indicada.',
    ],
    tip: 'Cuenta los cordones en relieve en lugar de las vueltas: cada uno equivale a 2 vueltas. El punto bobo no se enrolla y se ve igual por los dos lados.',
  },
  'kn-rib': {
    name: 'Elástico (1x1 y 2x2)',
    abbr: [],
    steps: [
      'Monta un número impar de puntos para el elástico 1x1, o un múltiplo de 4 más 2 para el elástico 2x2: así los dos bordes quedan iguales.',
      'Elástico 1x1: alterna 1 punto derecho y 1 punto revés hasta el último punto, y téjelo del derecho.',
      'Elástico 2x2: alterna 2 puntos derechos y 2 puntos revés hasta los 2 últimos puntos, y téjelos del derecho.',
      'En cada cambio, pasa la hebra entre las dos agujas: hacia delante antes de un punto revés, hacia atrás antes de un punto derecho.',
      'Gira la labor.',
      'Teje cada punto como se presenta: del derecho los que muestran una V, del revés los que muestran un nudo.',
      'Repite los pasos 5 y 6 hasta la altura indicada.',
      'En redondo, monta un número par de puntos para el elástico 1x1, un múltiplo de 4 para el 2x2, y teje cada vuelta como la primera.',
    ],
    tip: 'Un punto de más junto a un pequeño agujero indica que la hebra pasó por encima de la aguja en lugar de pasar entre las dos: formó una lazada. Por el derecho, las columnas de V deben quedar bien alineadas.',
  },
  'kn-seed': {
    name: 'Punto de arroz',
    abbr: [],
    steps: [
      'Monta un número impar de puntos.',
      'Teje 1 punto derecho.',
      'Lleva la hebra hacia delante entre las agujas y teje 1 punto revés.',
      'Vuelve a pasar la hebra hacia atrás entre las agujas.',
      'Repite los pasos 2 a 4 hasta el último punto, y téjelo del derecho.',
      'Gira la labor y teje cada vuelta de la misma forma: empieza y termina con 1 punto derecho.',
      'Comprueba sobre la marcha: un punto que muestra una V se teje del revés, un punto que muestra un nudo se teje del derecho.',
      'En redondo, sobre un número par de puntos, aplica la misma regla en cada vuelta.',
    ],
    tip: 'Si se forman columnas, estás tejiendo los puntos como se presentan: eso es elástico 1x1. Los patrones en inglés dicen seed stitch, o moss stitch en el Reino Unido; en Estados Unidos, moss stitch es una variante que solo se desplaza cada 2 vueltas.',
  },
  'kn-cable': {
    name: 'Ocho o trenza (4 puntos, con aguja auxiliar)',
    abbr: [],
    steps: [
      'En una vuelta del derecho, teje hasta los 4 puntos del ocho.',
      'Desliza los 2 primeros puntos del ocho a la aguja auxiliar, como para tejerlos del revés.',
      'Deja colgar la aguja auxiliar por detrás de la labor: sus puntos pasarán por debajo y el ocho se cruzará hacia la derecha.',
      'Teje del derecho los 2 puntos siguientes de la aguja izquierda, apretando un poco el primero.',
      'Teje del derecho los 2 puntos de la aguja auxiliar, empezando por el que deslizaste primero.',
      'Para un ocho cruzado hacia la izquierda, haz los mismos gestos con la aguja auxiliar por delante de la labor en el paso 3.',
      'Entre dos cruces, teje los puntos como se presentan y vuelve a cruzar en la vuelta que indique el patrón.',
    ],
    tip: 'Si el ocho gira hacia el lado equivocado, mira dónde dejaste la aguja auxiliar: detrás cruza a la derecha, delante a la izquierda. Desliza los puntos sin retorcerlos, o quedarán cruzados en la base.',
  },
  'kn-short-rows-german': {
    name: 'Vueltas cortas alemanas',
    abbr: [],
    steps: [
      'Teje hasta el punto de giro que indica el patrón.',
      'Gira la labor: los puntos sin tejer esperan en la aguja derecha.',
      'Lleva la hebra hacia delante de la labor, si no está ya ahí.',
      'Desliza el primer punto a la aguja derecha, como para tejerlo del revés.',
      'Tira de la hebra hacia arriba y luego hacia atrás, por encima de la aguja derecha, hasta que el punto deslizado muestre dos hebras en la aguja: es el punto doble.',
      'Mantén la hebra tensa; si el punto siguiente se teje del revés, vuelve a llevarla hacia delante entre las agujas.',
      'Teje hasta el siguiente punto de giro y repite los pasos 2 a 6.',
      'Cuando llegues a un punto doble, introduce la aguja en sus dos hebras a la vez.',
      'Téjelas juntas como un solo punto, del derecho o del revés según la vuelta.',
    ],
    tip: 'Un punto doble cuenta como 1 punto, no como 2. Tira con firmeza de la hebra en el paso 5: si queda floja, deja un agujero en el giro.',
  },
  'kn-pick-up': {
    name: 'Recoger puntos',
    abbr: [],
    steps: [
      'Sujeta la labor con el derecho hacia ti, el borde donde vas a recoger arriba, y empieza por la esquina derecha.',
      'En un borde de montaje o de cierre, introduce la aguja derecha de delante hacia atrás en el centro de la V del punto que recorre el borde.',
      'En un borde lateral, introdúcela de delante hacia atrás entre el punto de orillo y su vecino, a un punto entero del borde.',
      'Pasa la hebra del ovillo alrededor de la aguja derecha, como para un punto derecho.',
      'Saca la lazada hacia delante: 1 punto queda recogido y tejido en la aguja derecha.',
      'En un borde de montaje o de cierre, repite en cada punto: 1 punto recogido por cada punto del borde.',
      'En un borde lateral de punto jersey, recoge 3 puntos por cada 4 vueltas saltando 1 vuelta de cada 4: un punto es más ancho de lo que mide de alto una vuelta.',
      'En un borde lateral de punto bobo, recoge 1 punto por cada cordón.',
    ],
    tip: 'Para repartir los puntos, divide el borde en partes iguales con marcadores y recoge el mismo número de puntos en cada una. Un agujero indica un punto recogido demasiado cerca del borde, en medio punto.',
  },
  'kn-kitchener': {
    name: 'Punto Kitchener (injerto)',
    abbr: [],
    steps: [
      'Reparte los puntos entre dos agujas, los mismos en cada una, y sujétalas en paralelo, revés contra revés, con las puntas hacia la derecha.',
      'Corta la hebra dejando 3 a 4 veces el ancho que vas a unir, enhébrala en una aguja lanera y comprueba que sale de la aguja de atrás.',
      'Preparación: introduce la aguja lanera en el primer punto de la aguja de delante como para tejerlo del revés, pasa la hebra y déjalo en la aguja.',
      'Introdúcela en el primer punto de la aguja de atrás como para tejerlo del derecho, pasa la hebra y déjalo en la aguja.',
      'Aguja de delante: introduce la aguja lanera en el primer punto como para tejerlo del derecho y sácalo de la aguja sin pasar la hebra.',
      'Introdúcela en el punto siguiente de la aguja de delante como para tejerlo del revés; pasa la hebra y déjalo en la aguja.',
      'Aguja de atrás: introduce la aguja lanera en el primer punto como para tejerlo del revés y sácalo de la aguja sin pasar la hebra.',
      'Introdúcela en el punto siguiente de la aguja de atrás como para tejerlo del derecho; pasa la hebra y déjalo en la aguja.',
      'Repite los pasos 5 a 8 hasta que quede 1 punto en cada aguja, tirando de la hebra solo lo justo para que cada puntada tenga el tamaño de un punto.',
      'Termina con el punto de delante, tomado del derecho y sacado, y luego el de atrás, tomado del revés y sacado; remata la hebra.',
    ],
    tip: 'Completa siempre la serie de los pasos 5 a 8 antes de dejar la labor: si no, puedes retomarla en el gesto equivocado. Si la costura se nota, ajusta la tensión puntada a puntada para que se parezca a la vuelta vecina.',
  },
}
