// Fiches du mémo en français (langue de référence). Rédigées pour Rowtine : aucune
// reprise de texte extérieur. Clés = identifiants de catalog.js.
export const STITCH_MEMO_FR = {
  'cr-ch': {
    name: 'Chaînette (maille en l’air)',
    abbr: ['ml'],
    steps: [
      'Forme une boucle avec le fil, à une dizaine de centimètres du bout.',
      'Tire une boucle du fil de la pelote à travers cette boucle : c’est le nœud coulant.',
      'Glisse le nœud coulant sur le crochet et serre-le sans l’étrangler.',
      'Fais un jeté.',
      'Ramène le fil à travers la boucle du crochet : tu as fait 1 maille en l’air.',
      'Répète le jeté et le passage du fil jusqu’au nombre de mailles demandé.',
    ],
    tip: 'Ne compte ni le nœud coulant ni la boucle sur le crochet : compte les petits V de la chaînette, sur l’endroit.',
  },
  'cr-slst': {
    name: 'Maille coulée',
    abbr: ['mc'],
    steps: [
      'Pique le crochet dans la maille suivante, sous les deux brins.',
      'Fais un jeté.',
      'Ramène le fil à travers la maille et la boucle du crochet d’un seul geste.',
    ],
    tip: 'La maille coulée n’ajoute presque pas de hauteur : elle sert à fermer un tour ou à te déplacer le long du rang. Garde-la souple, sinon tu auras du mal à piquer dedans au tour suivant.',
  },
  'cr-sc': {
    name: 'Maille serrée',
    abbr: ['ms'],
    steps: [
      'Pique le crochet dans la maille suivante, sous les deux brins.',
      'Fais un jeté et ramène le fil à travers la maille : tu as 2 boucles sur le crochet.',
      'Fais un nouveau jeté.',
      'Écoule les 2 boucles d’un seul coup.',
    ],
    tip: 'Au bout du rang, compte tes mailles : la maille serrée est courte, une maille oubliée se voit vite au rang suivant.',
  },
  'cr-hdc': {
    name: 'Demi-bride',
    abbr: ['db'],
    steps: [
      'Fais un jeté.',
      'Pique le crochet dans la maille suivante, sous les deux brins.',
      'Fais un jeté et ramène le fil à travers la maille : tu as 3 boucles sur le crochet.',
      'Fais un nouveau jeté.',
      'Écoule les 3 boucles d’un seul coup.',
    ],
    tip: 'En début de rang, la chaînette de tournant se fait avec 2 mailles en l’air. Selon le patron, elle compte ou non comme la première demi-bride : vérifie-le avant de piquer.',
  },
  'cr-dc': {
    name: 'Bride',
    abbr: ['br'],
    steps: [
      'Fais un jeté.',
      'Pique le crochet dans la maille suivante, sous les deux brins.',
      'Fais un jeté et ramène le fil à travers la maille : tu as 3 boucles sur le crochet.',
      'Fais un jeté et écoule les 2 premières boucles : il en reste 2.',
      'Fais un jeté et écoule les 2 dernières boucles.',
    ],
    tip: 'La chaînette de tournant de 3 mailles en l’air compte en général comme la première bride : fais alors la bride suivante dans la deuxième maille du rang, sinon l’ouvrage s’élargit.',
  },
  'cr-tr': {
    name: 'Double bride',
    abbr: ['dB'],
    steps: [
      'Fais deux jetés.',
      'Pique le crochet dans la maille suivante, sous les deux brins.',
      'Fais un jeté et ramène le fil à travers la maille : tu as 4 boucles sur le crochet.',
      'Fais un jeté et écoule 2 boucles : il en reste 3.',
      'Fais un jeté et écoule 2 boucles : il en reste 2.',
      'Fais un jeté et écoule les 2 dernières boucles.',
    ],
    tip: 'Tu écoules les boucles 2 par 2, trois fois de suite. En début de rang, la chaînette de tournant se fait avec 4 mailles en l’air.',
  },
  'cr-inc': {
    name: 'Augmentation',
    abbr: ['aug'],
    steps: [
      'Fais une maille serrée dans la maille suivante.',
      'Pique de nouveau le crochet dans cette même maille.',
      'Fais une deuxième maille serrée : une seule maille de base porte maintenant 2 mailles.',
    ],
    tip: 'Chaque augmentation ajoute 1 maille, et le geste est le même avec des brides. En rond, décale les augmentations d’un tour à l’autre, sinon le disque prend des angles.',
  },
  'cr-dec': {
    name: 'Diminution (2 mailles serrées écoulées ensemble)',
    abbr: ['dim'],
    steps: [
      'Pique le crochet dans la maille suivante.',
      'Fais un jeté et ramène le fil à travers la maille : tu as 2 boucles sur le crochet.',
      'Pique le crochet dans la maille d’après.',
      'Fais un jeté et ramène le fil à travers la maille : tu as 3 boucles sur le crochet.',
      'Fais un nouveau jeté.',
      'Écoule les 3 boucles d’un seul coup : 2 mailles n’en font plus qu’une.',
    ],
    tip: 'En amigurumi, la diminution invisible laisse moins de trou : pique dans les seuls brins avant des 2 mailles à la fois, puis termine comme une maille serrée.',
  },
  'cr-magic-ring': {
    name: 'Anneau magique',
    abbr: ['AM'],
    steps: [
      'Enroule le fil autour de deux doigts pour former une boucle, le bout croisé par-dessus le fil qui va à la pelote.',
      'Glisse le crochet dans la boucle, attrape le fil qui va à la pelote et ramène-le à travers.',
      'Fais 1 maille en l’air pour bloquer : elle ne compte pas comme une maille.',
      'Fais dans l’anneau le nombre de mailles serrées demandé, souvent 6, en piquant sous la boucle et le bout du fil ensemble.',
      'Tire sur le bout du fil pour refermer l’anneau.',
      'Ferme le tour par une maille coulée dans la première maille serrée, ou continue en spirale.',
    ],
    tip: 'Rentre le bout du fil en changeant plusieurs fois de direction : c’est lui qui tient l’anneau fermé, et s’il glisse, le centre se rouvre.',
  },
  'cr-rounds': {
    name: 'Travail en rond et en rangs',
    abbr: [],
    steps: [
      'En rangs, fais au bout du rang la chaînette de tournant : 1 maille en l’air pour des mailles serrées, 2 pour des demi-brides, 3 pour des brides.',
      'Retourne l’ouvrage et commence le rang suivant.',
      'En rond fermé, termine chaque tour par une maille coulée dans la première maille du tour.',
      'Fais la chaînette de hauteur du nouveau tour, puis continue sans retourner l’ouvrage.',
      'En spirale, ne ferme pas le tour : enchaîne directement dans la première maille du tour précédent.',
      'Place un marqueur dans la première maille de chaque tour et remonte-le à chaque nouveau tour.',
    ],
    tip: 'Selon le patron, la chaînette de tournant compte ou non comme une maille : relis la consigne, c’est la cause la plus fréquente d’un rang qui gagne ou perd une maille.',
  },
  'cr-flo-blo': {
    name: 'Brin avant, brin arrière',
    abbr: ['bav', 'barr'],
    steps: [
      'Regarde le haut de la maille : il forme un V couché, fait de deux brins.',
      'Repère le brin avant, le plus proche de toi, et le brin arrière, le plus éloigné.',
      'Pour travailler dans le brin avant, pique le crochet sous ce seul brin.',
      'Pour travailler dans le brin arrière, passe le crochet entre les deux brins et sous le seul brin arrière.',
      'Termine la maille comme d’habitude.',
    ],
    tip: 'Avant et arrière se lisent par rapport à toi, tel que tu tiens l’ouvrage, pas par rapport à l’endroit du travail. Le brin laissé libre forme une ligne en relief.',
  },
  'cr-color-change': {
    name: 'Changement de couleur',
    abbr: [],
    steps: [
      'Commence la dernière maille de l’ancienne couleur et arrête-toi avant son dernier jeté.',
      'Lâche l’ancienne couleur, en gardant une dizaine de centimètres de fil si tu la coupes.',
      'Prends la nouvelle couleur en laissant un bout d’une dizaine de centimètres.',
      'Fais le dernier jeté avec la nouvelle couleur et écoule les boucles : la maille est terminée.',
      'Continue avec la nouvelle couleur.',
      'À la fin, rentre les deux bouts, chacun dans des mailles de sa couleur.',
    ],
    tip: 'En rond fermé, change de couleur à la maille coulée de jonction : fais-la avec la nouvelle couleur, le raccord se voit moins.',
  },
  'cr-shell': {
    name: 'Coquille (éventail)',
    abbr: [],
    steps: [
      'Fais 1 maille serrée dans la première maille.',
      'Saute le nombre de mailles indiqué par le patron, souvent 2.',
      'Fais dans la maille suivante le nombre de brides demandé, souvent 5.',
      'Saute de nouveau le même nombre de mailles.',
      'Fais une maille serrée dans la maille suivante pour fixer la coquille.',
      'Répète les étapes 2 à 5 jusqu’au bout du rang.',
    ],
    tip: 'Avec 5 brides et 2 mailles sautées de chaque côté, chaque motif prend 6 mailles : le rang de base doit compter un multiple de 6 mailles, plus 1, sinon la dernière coquille tombe de travers.',
  },
  'cr-picot': {
    name: 'Picot',
    abbr: [],
    steps: [
      'Fais 3 mailles en l’air, ou le nombre indiqué par le patron.',
      'Pique le crochet dans la première de ces mailles en l’air, la troisième à partir du crochet.',
      'Fais un jeté.',
      'Ramène le fil à travers la maille et la boucle du crochet d’un seul geste : le picot est fermé par une maille coulée.',
    ],
    tip: 'Certains patrons ferment le picot dans le haut de la maille qui le précède plutôt que dans la chaînette : suis la consigne, la base du picot ne tombe pas au même endroit.',
  },
  'cr-popcorn': {
    name: 'Point popcorn',
    abbr: [],
    steps: [
      'Fais 5 brides dans la même maille, ou le nombre indiqué par le patron.',
      'Retire le crochet de la boucle et agrandis-la un peu pour qu’elle ne se défasse pas.',
      'Pique le crochet de l’avant vers l’arrière dans le haut de la première des 5 brides.',
      'Rattrape avec le crochet la boucle laissée en attente.',
      'Tire-la à travers le haut de la première bride : le groupe se referme et bombe vers l’avant.',
      'Fais 1 maille en l’air pour bloquer le popcorn.',
    ],
    tip: 'Le popcorn ressort du côté d’où tu repiques : de l’avant vers l’arrière, il bombe vers toi. Ne le confonds pas avec le point de bouillon (puff), dont les boucles sont écoulées ensemble.',
  },
  'cr-puff': {
    name: 'Point de bouillon (puff)',
    abbr: [],
    steps: [
      'Fais un jeté et pique le crochet dans la maille.',
      'Fais un jeté et ramène une boucle longue, à peu près à la hauteur d’une demi-bride.',
      'Répète ces deux gestes 3 fois de plus dans la même maille : tu as 9 boucles sur le crochet.',
      'Fais un jeté et écoule les 9 boucles d’un seul coup.',
      'Fais 1 maille en l’air pour fermer le point.',
    ],
    tip: 'Si les boucles refusent de passer, elles sont trop courtes ou trop serrées : allonge-les toutes à la même hauteur et maintiens-les contre le crochet avec l’index.',
  },
  'cr-post': {
    name: 'Bride en relief avant et arrière',
    abbr: ['bRav', 'bRar'],
    steps: [
      'Fais un jeté.',
      'Pour le relief avant, pique de l’avant vers l’arrière d’un côté du pied de la bride du rang précédent, puis ressors vers l’avant de l’autre côté : le crochet passe derrière le pied.',
      'Fais un jeté et ramène une boucle autour du pied : tu as 3 boucles sur le crochet.',
      'Fais un jeté et écoule les 2 premières boucles.',
      'Fais un jeté et écoule les 2 dernières boucles.',
      'Pour le relief arrière, après le jeté, pique de l’arrière vers l’avant d’un côté du pied, puis ressors vers l’arrière de l’autre côté : le crochet passe devant le pied.',
      'Termine la maille comme pour le relief avant, avec les étapes 3 à 5.',
    ],
    tip: 'Ne travaille pas le haut de la maille dont tu as entouré le pied : il est caché derrière le relief, et le sauter garde le bon nombre de mailles.',
  },
  'kn-co-long-tail': {
    name: 'Montage à longue queue (montage continental)',
    abbr: [],
    steps: [
      'Mesure une longueur de fil libre pour la queue : compte environ 2 à 3 cm par maille à monter, selon l’épaisseur du fil.',
      'Fais un nœud coulant à cet endroit et place-le sur l’aiguille : il compte comme la première maille.',
      'Tiens l’aiguille dans la main droite, passe la queue autour du pouce gauche et le fil de la pelote sur l’index gauche, les deux bouts retenus dans la paume.',
      'Passe la pointe de l’aiguille de bas en haut dans la boucle du pouce, sous le brin avant.',
      'Attrape avec la pointe le brin de l’index, en passant par-dessus.',
      'Ramène ce brin à travers la boucle du pouce.',
      'Lâche la boucle du pouce, puis écarte le pouce sous la queue pour resserrer la maille sur l’aiguille.',
      'Répète les étapes 4 à 7 jusqu’au nombre de mailles demandé.',
    ],
    tip: 'Si la queue manque avant la fin, recommence avec une queue plus longue plutôt que de rajouter du fil. Resserre sans étrangler l’aiguille : les mailles doivent pouvoir glisser.',
  },
  'kn-co-tubular': {
    name: 'Montage tubulaire (à l’italienne)',
    abbr: [],
    steps: [
      'Prends une aiguille 1 ou 2 tailles plus fine que pour les côtes, et laisse une queue de 3 à 4 fois la largeur à monter.',
      'Fais un nœud coulant et place-le sur l’aiguille, tenue dans la main droite : il compte comme la première maille.',
      'Tiens les fils comme pour le montage à longue queue : la queue sur le pouce gauche, le fil de la pelote sur l’index gauche.',
      'Maille envers : plonge la pointe de l’aiguille sous le fil de l’index, en venant de l’arrière, pour la placer entre les deux fils.',
      'Accroche le fil du pouce en passant par-dessus puis devant lui, et ressors par le même chemin, sous le fil de l’index : la maille envers est sur l’aiguille.',
      'Maille endroit : plonge la pointe sous le fil du pouce, en venant de l’avant, pour la placer entre les deux fils.',
      'Accroche le fil de l’index en passant par-dessus puis derrière lui, et ressors par le même chemin, sous le fil du pouce : la maille endroit est sur l’aiguille.',
      'Répète les étapes 4 à 7 jusqu’au nombre de mailles demandé, en alternant toujours envers et endroit.',
      'Tricote 2 rangs tubulaires en glissant à l’envers, fil devant, les mailles qui se présentent à l’envers ; au 1er rang, si la première maille se présente à l’endroit, tricote-la normalement, et tricote toutes les autres mailles endroit par le brin arrière ; au 2e rang, tricote les mailles endroit normalement.',
      'Passe aux aiguilles des côtes et continue en côtes 1/1.',
    ],
    tip: 'Les mailles endroit sortent du montage tournées sur l’aiguille : les tricoter par le brin arrière au 1er rang les remet dans le bon sens ; seule la première, si elle se présente à l’endroit, se tricote normalement. Monte à plat, et ne joins en rond qu’après les 2 rangs tubulaires.',
  },
  'kn-co-cable': {
    name: 'Montage tricoté (entre les mailles)',
    abbr: [],
    steps: [
      'Tiens dans la main gauche l’aiguille qui porte les mailles, le fil derrière l’ouvrage.',
      'Pique l’aiguille droite entre les 2 premières mailles de l’aiguille gauche, de l’avant vers l’arrière.',
      'Passe le fil autour de l’aiguille droite, comme pour une maille endroit.',
      'Ramène la boucle vers l’avant, entre les 2 mailles.',
      'Glisse cette boucle sur l’aiguille gauche sans la tordre : c’est la nouvelle première maille.',
      'Retire l’aiguille droite et tire doucement sur le fil pour ajuster la maille.',
      'Répète les étapes 2 à 6 jusqu’au nombre de mailles à ajouter.',
    ],
    tip: 'Pour partir d’une aiguille vide, fais un nœud coulant, tricote-le à l’endroit sans le lâcher et glisse la boucle obtenue sur l’aiguille gauche : tu as les 2 mailles de départ. Ne serre pas trop, ce montage est déjà ferme.',
  },
  'kn-bo': {
    name: 'Rabattage classique',
    abbr: ['rab.'],
    steps: [
      'Tricote les 2 premières mailles comme elles se présentent, à l’endroit ou à l’envers.',
      'Pique l’aiguille gauche dans la première maille tricotée, la plus éloignée de la pointe de l’aiguille droite.',
      'Fais-la passer par-dessus la deuxième maille et hors de l’aiguille droite : 1 maille est rabattue.',
      'Tricote la maille suivante : tu as de nouveau 2 mailles sur l’aiguille droite.',
      'Répète les étapes 2 à 4 jusqu’à ce qu’il ne reste qu’1 maille sur l’aiguille droite.',
      'Coupe le fil en laissant une quinzaine de centimètres.',
      'Passe le bout dans la dernière maille et tire pour la fermer.',
    ],
    tip: 'Rabats sans serrer, au besoin avec une aiguille plus grosse : un bord trop tendu fronce. Quand tu rabats quelques mailles en début de rang, la maille qui reste sur l’aiguille droite compte comme la première des mailles suivantes.',
  },
  'kn-bo-tubular': {
    name: 'Rabattage tubulaire (à l’italienne, continental)',
    abbr: [],
    steps: [
      'Coupe le fil en laissant 3 à 4 fois la largeur du bord, et enfile-le sur une aiguille à laine.',
      'Vérifie que la première maille de l’aiguille est une maille endroit : le rabattage commence par elle.',
      'Pique dans cette première maille comme pour la tricoter à l’envers, tire le fil et laisse-la sur l’aiguille.',
      'Prends la deuxième maille, une maille envers, par l’arrière de l’ouvrage : l’aiguille à laine passe de l’arrière vers l’avant entre les 2 premières mailles, puis pique dans la maille envers comme pour la tricoter à l’endroit ; tire le fil et laisse-la sur l’aiguille.',
      'Pique dans la première maille, une maille endroit, comme pour la tricoter à l’endroit, et fais-la glisser de l’aiguille sans tirer le fil.',
      'Saute la maille envers et pique dans la maille endroit suivante comme pour la tricoter à l’envers ; tire le fil et laisse-la sur l’aiguille.',
      'Pique dans la première maille, la maille envers sautée, comme pour la tricoter à l’envers, fais-la glisser de l’aiguille et tire le fil.',
      'Refais le geste de l’étape 4 dans la maille envers suivante.',
      'Répète les étapes 5 à 8 jusqu’à ce qu’il ne reste qu’1 maille sur l’aiguille, en tirant le fil juste assez pour que chaque point ait la taille d’une maille.',
      'Passe le fil dans la dernière maille comme pour la tricoter à l’envers, puis rentre-le.',
    ],
    tip: '« À l’italienne » et « continental » désignent ce même rabattage, réservé aux côtes 1/1. Pour un bord encore plus rond, tricote d’abord 2 rangs tubulaires : les mailles endroit à l’endroit, les mailles envers glissées à l’envers, fil devant.',
  },
  'kn-knit': {
    name: 'Maille endroit',
    abbr: ['m. end.', 'end.'],
    steps: [
      'Tiens l’aiguille avec les mailles dans ta main gauche, le fil derrière l’ouvrage.',
      'Pique l’aiguille droite dans la première maille, de l’avant vers l’arrière, de gauche à droite.',
      'Passe le fil autour de l’aiguille droite, de la gauche vers la droite.',
      'Ramène cette boucle vers l’avant à travers la maille.',
      'Laisse glisser la maille de l’aiguille gauche : la nouvelle maille est sur l’aiguille droite.',
    ],
    tip: 'Ne serre pas le fil : une maille trop tendue se tricote mal au rang suivant.',
  },
  'kn-purl': {
    name: 'Maille envers',
    abbr: ['m. env.', 'env.'],
    steps: [
      'Tiens l’aiguille avec les mailles dans ta main gauche, le fil devant l’ouvrage.',
      'Pique l’aiguille droite dans la première maille, de droite à gauche, en passant devant l’aiguille gauche.',
      'Passe le fil par-dessus l’aiguille droite, de l’avant vers l’arrière, puis ramène-le devant entre les deux aiguilles.',
      'Ramène cette boucle vers l’arrière à travers la maille.',
      'Laisse glisser la maille de l’aiguille gauche : la nouvelle maille est sur l’aiguille droite.',
    ],
    tip: 'Garde le fil devant d’une maille envers à l’autre : s’il passe par-dessus l’aiguille entre deux mailles, il ajoute une maille et laisse un trou.',
  },
  'kn-tbl': {
    name: 'Maille torse',
    abbr: ['m. end. torse'],
    steps: [
      'Place le fil derrière l’ouvrage, comme pour une maille endroit.',
      'Pique l’aiguille droite dans le brin arrière de la première maille, de droite à gauche, en passant derrière l’aiguille gauche.',
      'Passe le fil autour de l’aiguille droite, comme pour une maille endroit.',
      'Ramène la boucle vers l’avant à travers la maille.',
      'Laisse glisser la maille de l’aiguille gauche : sa base est croisée.',
    ],
    tip: 'À l’envers, pique dans le brin arrière de gauche à droite, par l’arrière, puis tricote la maille à l’envers. Si la base de la maille n’est pas croisée, tu as piqué dans le brin avant.',
  },
  'kn-slip': {
    name: 'Glisser une maille',
    abbr: ['gl.'],
    steps: [
      'Place le fil du côté demandé par le patron, devant ou derrière l’ouvrage ; sans précision, laisse-le du côté de l’envers du travail.',
      'Pique l’aiguille droite dans la maille, de droite à gauche, comme pour la tricoter à l’envers.',
      'Fais passer la maille sur l’aiguille droite sans la tricoter.',
      'Tricote la maille suivante sans tirer sur le fil qui passe devant ou derrière la maille glissée.',
    ],
    tip: 'Sans précision, glisse à l’envers : la maille garde son sens. Glisse à l’endroit, en piquant de gauche à droite, seulement quand le patron le demande, comme dans les diminutions.',
  },
  'kn-yo': {
    name: 'Jeté',
    abbr: ['j.'],
    steps: [
      'Si le fil est derrière l’ouvrage, ramène-le devant, entre les deux aiguilles.',
      'Si la maille suivante est une maille endroit, tricote-la : le fil passe par-dessus l’aiguille droite et forme le jeté.',
      'Si c’est une maille envers, fais d’abord faire au fil un tour complet de l’aiguille droite : par-dessus vers l’arrière, puis entre les aiguilles vers l’avant.',
      'Tricote alors la maille envers.',
      'Au rang suivant, tricote le jeté comme une maille ordinaire : il ajoute 1 maille et laisse un petit trou.',
    ],
    tip: 'Tricote le jeté par le brin avant : pris par le brin arrière, il se tord et le trou se referme. Un jeté se perd facilement, compte tes mailles à la fin du rang.',
  },
  'kn-k2tog': {
    name: '2 mailles ensemble à l’endroit',
    abbr: ['2 m. ens.', '2 m. ens. end.'],
    steps: [
      'Place le fil derrière l’ouvrage, comme pour une maille endroit.',
      'Pique l’aiguille droite dans les 2 mailles suivantes à la fois, de l’avant vers l’arrière.',
      'Passe le fil autour de l’aiguille droite.',
      'Ramène la boucle à travers les 2 mailles.',
      'Laisse glisser les 2 mailles de l’aiguille gauche : elles n’en font plus qu’une, inclinée vers la droite.',
    ],
    tip: 'Le nombre de mailles baisse de 1. Compte-les à la fin du rang pour t’assurer de tomber juste.',
  },
  'kn-p2tog': {
    name: '2 mailles ensemble à l’envers',
    abbr: ['2 m. ens. env.'],
    steps: [
      'Place le fil devant l’ouvrage, comme pour une maille envers.',
      'Pique l’aiguille droite dans les 2 mailles suivantes à la fois, de droite à gauche, comme pour les tricoter à l’envers.',
      'Passe le fil par-dessus l’aiguille droite, de l’avant vers l’arrière, puis ramène-le devant entre les deux aiguilles.',
      'Ramène la boucle vers l’arrière à travers les 2 mailles.',
      'Laisse glisser les 2 mailles de l’aiguille gauche : elles n’en font plus qu’une.',
    ],
    tip: 'Vue de l’endroit, cette diminution penche vers la droite, comme 2 mailles ensemble à l’endroit : c’est sa jumelle pour les rangs envers.',
  },
  'kn-skp': {
    name: 'Surjet simple',
    abbr: ['surj. s.'],
    steps: [
      'Glisse 1 maille sur l’aiguille droite en piquant comme pour la tricoter à l’endroit, sans la tricoter.',
      'Tricote la maille suivante à l’endroit.',
      'Pique l’aiguille gauche dans la maille glissée, par l’avant.',
      'Fais-la passer par-dessus la maille tricotée et hors de l’aiguille droite : 2 mailles n’en font plus qu’une, inclinée vers la gauche.',
    ],
    tip: 'Ce n’est pas le ssk, décrit à part : ici une maille est rabattue par-dessus l’autre, et la diminution est un peu plus lâche. Certains patrons appellent « surjet simple » l’un ou l’autre geste : lis leur légende.',
  },
  'kn-ssk': {
    name: 'Glisser, glisser, tricoter (ssk)',
    abbr: ['ssk'],
    steps: [
      'Glisse 1 maille sur l’aiguille droite en piquant comme pour la tricoter à l’endroit.',
      'Glisse de la même façon la maille suivante, séparément de la première.',
      'Pique l’aiguille gauche dans le brin avant des 2 mailles glissées, de gauche à droite : l’aiguille droite reste derrière.',
      'Passe le fil autour de l’aiguille droite, comme pour une maille endroit.',
      'Ramène la boucle à travers les 2 mailles et laisse-les glisser de l’aiguille gauche : elles n’en font plus qu’une, inclinée vers la gauche.',
    ],
    tip: 'Ce geste revient à tricoter ensemble, par le brin arrière, 2 mailles glissées une à une à l’endroit. Ce n’est pas le surjet simple, décrit à part : aucune maille n’est rabattue, la diminution est plus plate.',
  },
  'kn-cdd': {
    name: 'Surjet double centré',
    abbr: [],
    steps: [
      'Glisse 2 mailles ensemble sur l’aiguille droite, en piquant dans les deux à la fois comme pour les tricoter ensemble à l’endroit.',
      'Tricote la maille suivante à l’endroit.',
      'Pique l’aiguille gauche dans les 2 mailles glissées, par l’avant.',
      'Fais-les passer ensemble par-dessus la maille tricotée et hors de l’aiguille droite : 3 mailles n’en font plus qu’une, et celle du milieu reste droite, au-dessus.',
    ],
    tip: 'Glisse les 2 mailles ensemble, pas une à une, sinon la maille du milieu ne reste pas au-dessus. Ne le confonds pas avec le surjet double non centré (1 maille glissée, 2 mailles ensemble, maille glissée rabattue), qui penche vers la gauche.',
  },
  'kn-m1': {
    name: 'Augmentation intercalaire (gauche et droite)',
    abbr: [],
    steps: [
      'Repère le brin horizontal tendu entre la dernière maille de l’aiguille droite et la première de l’aiguille gauche.',
      'Pour l’augmentation penchée à gauche, soulève ce brin avec l’aiguille gauche, en piquant de l’avant vers l’arrière.',
      'Tricote-le à l’endroit par le brin arrière : la nouvelle maille se croise et penche vers la gauche.',
      'Pour l’augmentation penchée à droite, soulève le brin avec l’aiguille gauche, en piquant de l’arrière vers l’avant.',
      'Tricote-le à l’endroit par le brin avant : la nouvelle maille se croise et penche vers la droite.',
    ],
    tip: 'Si un trou apparaît, le brin ne s’est pas croisé : tu l’as tricoté par le mauvais côté. Chaque augmentation ajoute 1 maille.',
  },
  'kn-kfb': {
    name: 'Augmentation dans le brin avant et arrière',
    abbr: [],
    steps: [
      'Tricote la maille suivante à l’endroit, sans la laisser glisser de l’aiguille gauche.',
      'Pique l’aiguille droite dans le brin arrière de cette même maille, de droite à gauche, en passant derrière l’aiguille gauche.',
      'Passe le fil autour de l’aiguille droite et ramène la boucle à travers la maille.',
      'Laisse glisser la maille de l’aiguille gauche : tu as 2 mailles sur l’aiguille droite.',
    ],
    tip: 'La deuxième maille laisse une petite barrette horizontale à sa base : c’est normal, et c’est ainsi que tu repères l’augmentation. Chaque augmentation ajoute 1 maille.',
  },
  'kn-stockinette': {
    name: 'Jersey',
    abbr: ['jersey end.', 'jers.'],
    steps: [
      'Monte le nombre de mailles demandé.',
      'Tricote toutes les mailles à l’endroit : c’est un rang endroit.',
      'Tourne l’ouvrage.',
      'Tricote toutes les mailles à l’envers : c’est un rang envers.',
      'Tourne l’ouvrage.',
      'Répète les étapes 2 à 5 jusqu’à la hauteur demandée.',
      'En rond, tricote tous les tours à l’endroit, sans jamais tourner l’ouvrage.',
    ],
    tip: 'L’endroit montre des colonnes de V, l’envers des rangées de petites bosses ; quand c’est ce côté qui se voit, le patron parle de jersey envers. Le jersey roule sur les bords : une bordure de côtes ou de point mousse le garde à plat.',
  },
  'kn-garter': {
    name: 'Point mousse',
    abbr: ['pt mousse'],
    steps: [
      'Monte le nombre de mailles demandé.',
      'Tricote toutes les mailles à l’endroit.',
      'Tourne l’ouvrage.',
      'Répète les étapes 2 et 3 : à plat, tous les rangs se tricotent à l’endroit.',
      'En rond, tricote un tour à l’endroit.',
      'Tricote le tour suivant à l’envers.',
      'Répète les étapes 5 et 6 jusqu’à la hauteur demandée.',
    ],
    tip: 'Compte les sillons en relief plutôt que les rangs : chacun vaut 2 rangs. Le point mousse ne roule pas et se ressemble des deux côtés.',
  },
  'kn-rib': {
    name: 'Côtes 1/1 et 2/2',
    abbr: [],
    steps: [
      'Monte un nombre impair de mailles pour les côtes 1/1, ou un multiple de 4 plus 2 pour les côtes 2/2 : les deux bords seront pareils.',
      'Côtes 1/1 : alterne 1 maille endroit et 1 maille envers jusqu’à la dernière maille, que tu tricotes à l’endroit.',
      'Côtes 2/2 : alterne 2 mailles endroit et 2 mailles envers jusqu’aux 2 dernières mailles, que tu tricotes à l’endroit.',
      'À chaque changement, fais passer le fil entre les deux aiguilles : devant avant une maille envers, derrière avant une maille endroit.',
      'Tourne l’ouvrage.',
      'Tricote chaque maille comme elle se présente : à l’endroit celles qui montrent un V, à l’envers celles qui montrent une bosse.',
      'Répète les étapes 5 et 6 jusqu’à la hauteur demandée.',
      'En rond, monte un nombre pair de mailles pour les côtes 1/1, un multiple de 4 pour les côtes 2/2, et tricote chaque tour comme le premier.',
    ],
    tip: 'Une maille en trop avec un petit trou veut dire que le fil est passé par-dessus l’aiguille au lieu de passer entre les deux : il a fait un jeté. Sur l’endroit, les colonnes de V doivent rester bien alignées.',
  },
  'kn-seed': {
    name: 'Point de riz',
    abbr: ['pt de riz'],
    steps: [
      'Monte un nombre impair de mailles.',
      'Tricote 1 maille endroit.',
      'Ramène le fil devant, entre les aiguilles, et tricote 1 maille envers.',
      'Repasse le fil derrière, entre les aiguilles.',
      'Répète les étapes 2 à 4 jusqu’à la dernière maille, et tricote-la à l’endroit.',
      'Tourne l’ouvrage et tricote chaque rang de la même façon : il commence et finit par 1 maille endroit.',
      'Vérifie au fil du rang : une maille qui montre un V se tricote à l’envers, une maille qui montre une bosse se tricote à l’endroit.',
      'En rond, sur un nombre pair de mailles, applique cette même règle à chaque tour.',
    ],
    tip: 'Si des colonnes se forment, tu tricotes les mailles comme elles se présentent : ce sont des côtes 1/1. Les patrons en anglais disent seed stitch, ou moss stitch au Royaume-Uni ; aux États-Unis, moss stitch désigne une variante qui ne se décale que tous les 2 rangs.',
  },
  'kn-cable': {
    name: 'Torsade (4 mailles, aiguille auxiliaire)',
    abbr: [],
    steps: [
      'Sur un rang endroit, tricote jusqu’aux 4 mailles de la torsade.',
      'Glisse les 2 premières mailles de la torsade sur l’aiguille auxiliaire, en piquant comme pour les tricoter à l’envers.',
      'Laisse pendre l’aiguille auxiliaire derrière l’ouvrage : ses mailles passeront dessous, et la torsade croisera vers la droite.',
      'Tricote à l’endroit les 2 mailles suivantes de l’aiguille gauche, en serrant un peu la première.',
      'Tricote à l’endroit les 2 mailles de l’aiguille auxiliaire, en commençant par la première glissée.',
      'Pour une torsade croisée vers la gauche, fais les mêmes gestes en tenant l’aiguille auxiliaire devant l’ouvrage à l’étape 3.',
      'Entre deux croisements, tricote les mailles comme elles se présentent, et croise de nouveau au rang indiqué par le patron.',
    ],
    tip: 'Si la torsade tourne dans le mauvais sens, regarde où tu as mis l’aiguille auxiliaire : derrière, elle croise à droite ; devant, à gauche. Glisse les mailles sans les tordre : tordues, elles restent croisées à leur base.',
  },
  'kn-short-rows-german': {
    name: 'Rangs raccourcis à l’allemande',
    abbr: [],
    steps: [
      'Tricote jusqu’au point de retournement indiqué par le patron.',
      'Tourne l’ouvrage : les mailles non tricotées restent en attente sur l’aiguille droite.',
      'Ramène le fil devant l’ouvrage, s’il n’y est pas déjà.',
      'Glisse la première maille sur l’aiguille droite, en piquant comme pour la tricoter à l’envers.',
      'Tire le fil vers le haut puis vers l’arrière, par-dessus l’aiguille droite, jusqu’à ce que la maille glissée montre deux brins sur l’aiguille : c’est la maille double.',
      'Garde le fil tendu ; si la maille suivante se tricote à l’envers, ramène-le devant, entre les aiguilles.',
      'Tricote jusqu’au retournement suivant et refais les étapes 2 à 6.',
      'Quand tu arrives sur une maille double, pique dans ses deux brins à la fois.',
      'Tricote-les ensemble, comme une seule maille, à l’endroit ou à l’envers selon le rang.',
    ],
    tip: 'Une maille double compte pour 1 maille, pas pour 2. Tire franchement le fil à l’étape 5 : trop lâche, il laisse un trou au retournement.',
  },
  'kn-pick-up': {
    name: 'Relever des mailles',
    abbr: ['rel.'],
    steps: [
      'Tiens l’ouvrage endroit face à toi, le bord à relever en haut, et commence par le coin de droite.',
      'Sur un bord monté ou rabattu, pique l’aiguille droite de l’avant vers l’arrière au milieu du V de la maille qui longe le bord.',
      'Sur une lisière, pique de l’avant vers l’arrière entre la maille lisière et sa voisine, une maille entière à l’intérieur du bord.',
      'Enroule le fil de la pelote autour de l’aiguille droite, comme pour une maille endroit.',
      'Ramène la boucle vers l’avant : 1 maille est relevée et tricotée sur l’aiguille droite.',
      'Sur un bord monté ou rabattu, recommence dans chaque maille : 1 maille relevée par maille du bord.',
      'Sur une lisière de jersey, relève 3 mailles pour 4 rangs en sautant 1 rang sur 4 : une maille est plus large qu’un rang n’est haut.',
      'Sur une lisière de point mousse, relève 1 maille par sillon.',
    ],
    tip: 'Pour répartir les mailles, partage le bord en parts égales avec des marqueurs et relève le même nombre de mailles dans chacune. Un trou signale une maille relevée trop près du bord, dans une demi-maille.',
  },
  'kn-kitchener': {
    name: 'Grafting (greffe en mailles endroit, Kitchener)',
    abbr: [],
    steps: [
      'Répartis les mailles sur deux aiguilles, autant sur chacune, et tiens-les parallèles, envers contre envers, pointes vers la droite.',
      'Coupe le fil en laissant 3 à 4 fois la largeur à greffer, enfile-le sur une aiguille à laine et vérifie qu’il part de l’aiguille arrière.',
      'Mise en place : pique dans la première maille de l’aiguille avant comme pour la tricoter à l’envers, tire le fil et laisse-la sur l’aiguille.',
      'Pique dans la première maille de l’aiguille arrière comme pour la tricoter à l’endroit, tire le fil et laisse-la sur l’aiguille.',
      'Aiguille avant : pique dans la première maille comme pour la tricoter à l’endroit, et fais-la glisser de l’aiguille sans tirer le fil.',
      'Pique dans la maille suivante de l’aiguille avant comme pour la tricoter à l’envers ; tire le fil et laisse-la sur l’aiguille.',
      'Aiguille arrière : pique dans la première maille comme pour la tricoter à l’envers, et fais-la glisser de l’aiguille sans tirer le fil.',
      'Pique dans la maille suivante de l’aiguille arrière comme pour la tricoter à l’endroit ; tire le fil et laisse-la sur l’aiguille.',
      'Répète les étapes 5 à 8 jusqu’à ce qu’il ne reste qu’1 maille sur chaque aiguille, en tirant le fil juste assez pour que chaque point ait la taille d’une maille.',
      'Termine par la maille avant, piquée à l’endroit et lâchée, puis la maille arrière, piquée à l’envers et lâchée ; rentre le fil.',
    ],
    tip: 'Finis toujours la série des étapes 5 à 8 avant de poser l’ouvrage : sinon tu risques de reprendre au mauvais geste. Si la couture se voit, ajuste la tension point par point pour qu’elle ressemble au rang voisin.',
  },
}
